import type { Account, AccountStatus, SalesRep } from "./types";

type Seed = Omit<Account, "id"> & { status: AccountStatus };

const raw: Seed[] = [
  {
    name: "Woodpecker Furniture",
    owner: "Bhuvaneshwari",
    industry: "Other",
    month: "July 2026",
    status: "prospect",
    reason: "keerthana 11am friday",
    createdAt: "2026-07-22T10:00:00.000Z",
  },
  {
    name: "Page 3 Luxury Salon",
    owner: "Bhuvaneshwari",
    industry: "Beauty & Wellness",
    month: "July 2026",
    status: "prospect",
    reason: "Revanth Roy said not interested",
    createdAt: "2026-07-27T10:00:00.000Z",
  },
  {
    name: "Kohler India",
    owner: "Bhuvaneshwari",
    industry: "Other",
    month: "July 2026",
    status: "prospect",
    reason: "Nobody picked , sent Linkedin Connection",
    createdAt: "2026-07-27T10:05:00.000Z",
  },
  {
    name: "Dr. Agravat",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "prospect",
    reason: "Spoke in Hindi , then called again it was busy",
    createdAt: "2026-07-27T10:10:00.000Z",
  },
  {
    name: "white Forest",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "prospect",
    reason: "No body picked",
    createdAt: "2026-07-27T10:15:00.000Z",
  },
  {
    name: "Fasta Pizza",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "prospect",
    reason: "Follow up call made , message sent for venue details",
    createdAt: "2026-07-27T10:20:00.000Z",
  },
  {
    name: "style Spa",
    owner: "Bhuvaneshwari",
    industry: "Beauty & Wellness",
    month: "July 2026",
    status: "prospect",
    reason: "not picking busy",
    createdAt: "2026-07-22T10:05:00.000Z",
  },
  {
    name: "Madras coffee house",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "prospect",
    reason: "send me details to this number",
    createdAt: "2026-07-22T10:10:00.000Z",
  },
  {
    name: "Matram's South Indian coffee house",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "prospect",
    reason: "he has asked me to share details to his whatsapp - shared",
    createdAt: "2026-07-22T10:15:00.000Z",
  },
  {
    name: "Chai Waale",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "prospect",
    reason: "is not picking up",
    createdAt: "2026-07-22T10:20:00.000Z",
  },
  {
    name: "Fasta Pizza",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "prospect",
    reason: "did not picked",
    createdAt: "2026-07-22T10:25:00.000Z",
  },
  {
    name: "Narayana Health",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "prospect",
    reason: "not yet confirmed with the team",
    createdAt: "2026-07-17T10:35:00.000Z",
  },
  {
    name: "Welona",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "rejected",
    reason: "Rejected",
    createdAt: "2026-07-17T10:30:00.000Z",
  },
  {
    name: "Sangeetha Restaurant",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "prospect",
    reason: "did not picked",
    createdAt: "2026-07-17T10:25:00.000Z",
  },
  {
    name: "Saravana Bhavan",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "prospect",
    reason: "did not picked",
    createdAt: "2026-07-17T10:20:00.000Z",
  },
  {
    name: "Murugan Idly Shop",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "prospect",
    reason: "Prasad - 8007489000 shared his team members contact to speak with Vignesh 9840837127 - he is in Delhi when he gets back to chennai , will try to meet",
    createdAt: "2026-07-17T10:15:00.000Z",
  },
  {
    name: "Chai Waale",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "prospect",
    reason: "9940083169 - call back on monday",
    createdAt: "2026-07-17T10:10:00.000Z",
  },
  {
    name: "RJR Herbals",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "prospect",
    reason: "7871111115 - will call back Tamil Nadu and pondicherry",
    createdAt: "2026-07-17T10:05:00.000Z",
  },
  {
    name: "CK's Bakery",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "prospect",
    reason: "Manuranjith - Founder - 9176674771 - did not pick",
    createdAt: "2026-07-17T10:00:00.000Z",
  },
  {
    name: "Secure Hospitals",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "prospect",
    reason: "9886653167 -Ravi Shankar CMO - call me back on monday",
    createdAt: "2026-07-16T10:20:00.000Z",
  },
  {
    name: "Sukino Health Care",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "prospect",
    reason: "call back in 15minutes Suresh Naik - 8904829390 - did not pick the call",
    createdAt: "2026-07-16T10:15:00.000Z",
  },
  {
    name: "Namma Veedu Vasantha Bhavan",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "prospect",
    reason: "not picking",
    createdAt: "2026-07-16T10:10:00.000Z",
  },
  {
    name: "Shree Mithai",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "rejected",
    reason: "change status to rejected",
    createdAt: "2026-07-16T10:05:00.000Z",
  },
  {
    name: "Narayana Health",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "prospect",
    reason: "Spoke with internal team , need confirmation from their side",
    createdAt: "2026-07-16T10:00:00.000Z",
  },
  {
    name: "Pixies - The beauty Shop",
    owner: "Bhuvaneshwari",
    industry: "Beauty & Wellness",
    month: "July 2026",
    status: "qualified",
    reason: "Reminded him to attend the scheduled meeting for 1pm",
    createdAt: "2026-07-15T10:00:00.000Z",
  },
  {
    name: "Page3 luxury Salon",
    owner: "Bhuvaneshwari",
    industry: "Beauty & Wellness",
    month: "July 2026",
    status: "rejected",
    reason: "Mr. Revanth Roy said that that was not a need for them currently",
    createdAt: "2026-07-15T10:05:00.000Z",
  },
  {
    name: "Shree Mithai",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "rejected",
    reason: "Rejected status",
    createdAt: "2026-07-15T10:10:00.000Z",
  },
  {
    name: "Advantage Foods Pvt.Ltd",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "qualified",
    reason: "Tarun - CEO-9094007869- DID NOT PICK",
    createdAt: "2026-07-15T10:15:00.000Z",
  },
  {
    name: "wELONA HEALTH CARE",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "qualified",
    reason: "did not pick - send mail to Gourav - CEO - 7200012989 after asking him in whatsapp",
    createdAt: "2026-07-15T10:20:00.000Z",
  },
  {
    name: "Chai kings",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "qualified",
    reason: "Imthiyaz - Digital marketing Manager - we already use fame pilot - sent wa message with dck - circle back after enabling Swiggy and Zomato",
    createdAt: "2026-07-15T10:25:00.000Z",
  },
  {
    name: "Narayana Health",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "qualified",
    reason: "Busy will let you know",
    createdAt: "2026-07-15T10:30:00.000Z",
  },
  {
    name: "Coffee Mechanics",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "qualified",
    reason: "ganga - 9483543244 - currently our team is doing that message on WA i will revert if needed",
    createdAt: "2026-07-15T10:35:00.000Z",
  },
  {
    name: "Sri Chakra Fertility",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "prospect",
    reason: "Krishna Murthi Reddy - Head of OP and Marketing 9642431155, he is in a meeting , will get back later.",
    createdAt: "2026-07-13T10:00:00.000Z",
  },
  {
    name: "Zazzle Salons",
    owner: "Bhuvaneshwari",
    industry: "Beauty & Wellness",
    month: "July 2026",
    status: "prospect",
    reason: "Number Busy",
    createdAt: "2026-07-13T10:05:00.000Z",
  },
  {
    name: "Tea bench/Zwarma",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "prospect",
    reason: "Did not pickup - Dinesh - Founder - 9841784263",
    createdAt: "2026-07-13T10:10:00.000Z",
  },
  {
    name: "RMKV Silks",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "July 2026",
    status: "qualified",
    reason: "Will get back later",
    createdAt: "2026-07-13T10:15:00.000Z",
  },
  {
    name: "Fazta Pizza",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "prospect",
    reason: "Not yet answered",
    createdAt: "2026-07-13T10:20:00.000Z",
  },
  {
    name: "5K Car Care",
    owner: "Bhuvaneshwari",
    industry: "Automotive",
    month: "July 2026",
    status: "prospect",
    reason: "nobody picked",
    createdAt: "2026-07-13T10:25:00.000Z",
  },
  {
    name: "Slam Fitness",
    owner: "Bhuvaneshwari",
    industry: "Fitness & Wellness",
    month: "July 2026",
    status: "prospect",
    reason: "Nobody picked",
    createdAt: "2026-07-13T10:30:00.000Z",
  },
  {
    name: "Namma veedu Vasanta Bhavan",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "qualified",
    reason: "Call me after 4pm on 14.07.2026",
    createdAt: "2026-07-13T10:35:00.000Z",
  },
  {
    name: "Ajfan",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "qualified",
    reason: "Spoke through linkedin - he replied saying will get back after 3 days.",
    createdAt: "2026-07-13T10:40:00.000Z",
  },
  {
    name: "Fasta Pizza",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "qualified",
    reason: "Not Picked - Madhu Radhakrishnan - Spoke again - They are from perungudi - Asked for offline meeting",
    createdAt: "2026-07-10T10:00:00.000Z",
  },
  {
    name: "Odyssey",
    owner: "Bhuvaneshwari",
    industry: "Other",
    month: "July 2026",
    status: "qualified",
    reason: "Wrong Number",
    createdAt: "2026-07-10T10:05:00.000Z",
  },
  {
    name: "Pricol",
    owner: "Bhuvaneshwari",
    industry: "Other",
    month: "July 2026",
    status: "qualified",
    reason: "Siddhart Malhotra - Not interested",
    createdAt: "2026-07-10T10:10:00.000Z",
  },
  {
    name: "5k car care",
    owner: "Bhuvaneshwari",
    industry: "Automotive",
    month: "July 2026",
    status: "qualified",
    reason: "Praveen - did not pick , sent WA message",
    createdAt: "2026-07-10T10:15:00.000Z",
  },
  {
    name: "Relaxo Footwear",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "July 2026",
    status: "qualified",
    reason: "Jagrit Choudhar - 9199057171 - not required (have big team already)",
    createdAt: "2026-07-10T10:20:00.000Z",
  },
  {
    name: "RMKV Silks",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "July 2026",
    status: "qualified",
    reason: "He is nusy in the event work",
    createdAt: "2026-07-10T10:25:00.000Z",
  },
  {
    name: "Neeman's",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "July 2026",
    status: "prospect",
    reason: "Nobody picked up the call",
    createdAt: "2026-07-10T10:30:00.000Z",
  },
  {
    name: "Urbanwood",
    owner: "Bhuvaneshwari",
    industry: "Other",
    month: "July 2026",
    status: "prospect",
    reason: "Not reachable",
    createdAt: "2026-07-10T10:35:00.000Z",
  },
  {
    name: "Venkat ventre",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "qualified",
    reason: "sent message from WA asking for their availability to connect",
    createdAt: "2026-07-06T10:00:00.000Z",
  },
  {
    name: "Derma Vue Clinics",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "qualified",
    reason:
      "sent message from WA asking for their availability to connect - he replied saying 'send details' so i sent pitch deck",
    createdAt: "2026-07-06T10:05:00.000Z",
  },
  {
    name: "Narayana Health",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "qualified",
    reason:
      "Sent reminder message to connect for demo by 11.30am - follow up Mr.Udit by , july13th to 15th - Email to udit sent with deck or pre- recorded video",
    createdAt: "2026-07-06T10:10:00.000Z",
    reminderType: "followup",
    reminderDate: "2026-07-13T10:00:00.000Z",
  },
  {
    name: "Soch Apparels",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "July 2026",
    status: "qualified",
    reason:
      "Sent msg ti Srijita asking whether we can connect over the phone . - she said we dont have any scope of it",
    createdAt: "2026-07-06T10:15:00.000Z",
  },
  {
    name: "venkat centre",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "qualified",
    reason: "she is in meeting , will get back once done",
    createdAt: "2026-07-03T10:00:00.000Z",
  },
  {
    name: "Berkowits",
    owner: "Bhuvaneshwari",
    industry: "Beauty & Wellness",
    month: "July 2026",
    status: "qualified",
    reason: "Send me the details through whatsapp, will review or get back - sent deck through WA",
    createdAt: "2026-07-03T10:05:00.000Z",
  },
  {
    name: "Yatharth hospital",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "qualified",
    reason: "Cut the call halfway through it - Pankaj Kumar - 8860986692",
    createdAt: "2026-07-03T10:10:00.000Z",
  },
  {
    name: "Khazana Jewellery",
    owner: "Bhuvaneshwari",
    industry: "Jewellery Retail",
    month: "July 2026",
    status: "qualified",
    reason: "Did not pick - Jemma Yugini- 9442570373",
    createdAt: "2026-07-03T10:15:00.000Z",
  },
  {
    name: "Cothas",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "qualified",
    reason: "Expect",
    createdAt: "2026-07-03T10:20:00.000Z",
  },
  {
    name: "Chocolate Bash",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "qualified",
    reason: "Sent an email to Miran, Creative Director. No Indian contact number available.",
    createdAt: "2026-07-08T10:00:00.000Z",
  },
  {
    name: "5K Car Care",
    owner: "Bhuvaneshwari",
    industry: "Automotive",
    month: "July 2026",
    status: "qualified",
    reason:
      "Tried contacting the CEO but ended up speaking with Praveen (PRO). Call: 7094484650 WhatsApp: 7094442626. Asked to send WA message. Will review and connect with CEO tomorrow morning/evening.",
    createdAt: "2026-07-08T10:05:00.000Z",
  },
  {
    name: "Vandha Vettuvom",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "qualified",
    reason:
      "Contact: Akhil, Phone: 7845718318. Out of station. Asked to call back on Monday after 11:00 AM.",
    createdAt: "2026-07-08T10:10:00.000Z",
  },
  {
    name: "Burgerman",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "qualified",
    reason:
      "Contact: Ramesh, Phone: 9940169261, Position: COO. Handles operations. Asked to send an email to hello@burgerman.in.",
    createdAt: "2026-07-08T10:15:00.000Z",
  },
  {
    name: "Basics (Hasbro)",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "July 2026",
    status: "qualified",
    reason:
      "Contact: Suhail Sathar, Phone: 9841046796, Director. Referred to Promanage. Pricing for AI Brand Agent is high. Asked to send deck via WhatsApp.",
    createdAt: "2026-07-08T10:20:00.000Z",
  },
  {
    name: "Mysore Saree",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "July 2026",
    status: "qualified",
    reason: "Did not answer the call.",
    createdAt: "2026-07-08T10:25:00.000Z",
  },
  {
    name: "Topi Vappa Biryani",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "qualified",
    reason: "Spoke with the owner. No contact number available. Sent an email to the founder.",
    createdAt: "2026-07-08T10:30:00.000Z",
  },
  {
    name: "Mysore Saree Udyog",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "July 2026",
    status: "qualified",
    reason: "call back after 1 hour - did not pick sent him msg via WA",
    createdAt: "2026-07-07T10:00:00.000Z",
  },
  {
    name: "RMKV Silks",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "July 2026",
    status: "qualified",
    reason: "Will confirm by friday or Saturday",
    createdAt: "2026-07-07T10:05:00.000Z",
  },
  {
    name: "Saravana Stores",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "July 2026",
    status: "qualified",
    reason: "He is in meeting - told to send message",
    createdAt: "2026-07-07T10:10:00.000Z",
  },
  {
    name: "Lucid",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "qualified",
    reason: "didnt pick or call back after some times",
    createdAt: "2026-07-07T10:15:00.000Z",
  },
  {
    name: "Hitech",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "qualified",
    reason: "didnt pick or call back after some times",
    createdAt: "2026-07-07T10:20:00.000Z",
  },
  {
    name: "SRL Agilus",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "qualified",
    reason: "didnt pick or call back after some times",
    createdAt: "2026-07-07T10:25:00.000Z",
  },
  {
    name: "Go Colors",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "July 2026",
    status: "qualified",
    reason: "didnt pick or call back after some times",
    createdAt: "2026-07-07T10:30:00.000Z",
  },
  {
    name: "Twin Birds",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "July 2026",
    status: "qualified",
    reason: "didnt pick or call back after some times",
    createdAt: "2026-07-07T10:35:00.000Z",
  },
  {
    name: "BLiss club",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "July 2026",
    status: "qualified",
    reason: "didnt pick or call back after some times",
    createdAt: "2026-07-07T10:40:00.000Z",
  },
  {
    name: "Ajfan",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "July 2026",
    status: "prospect",
    reason: "linkedin Message to Muhammad has been sent",
    createdAt: "2026-07-02T10:00:00.000Z",
  },
  {
    name: "Berkowits hair and skin",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "prospect",
    reason:
      "Called Dhananjay - 8826397606 - but didnot pick up - call me around 11 am in the morning tomorrow (friday) - 03.07.2026",
    createdAt: "2026-07-02T10:05:00.000Z",
  },
  {
    name: "RMKV silks",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "July 2026",
    status: "prospect",
    reason: "sent deck via Whatsapp",
    createdAt: "2026-07-02T10:10:00.000Z",
  },
  {
    name: "Indira IVF",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "rejected",
    reason: "Not Interested , asked for feedback",
    createdAt: "2026-07-02T10:15:00.000Z",
  },
  {
    name: "Sakhiya skin cllinic",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "prospect",
    reason: "called again but without ring it said busy",
    createdAt: "2026-07-02T10:20:00.000Z",
  },
  {
    name: "Derma Vue",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "prospect",
    reason: "Did Not pick",
    createdAt: "2026-07-02T10:25:00.000Z",
  },
  {
    name: "Aster Mdcity",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "prospect",
    reason: "Follow up message on whatsapp",
    createdAt: "2026-07-02T10:30:00.000Z",
  },
  {
    name: "Sakhuya Skin Clinic",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "prospect",
    reason: "New lead Sahil Ramani, called by 4pm - dialled number is busy",
    createdAt: "2026-07-01T10:00:00.000Z",
  },
  {
    name: "DermaVue Clinics",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "prospect",
    reason: "Newlead Sarath Sivan, called by evening but it said busy",
    createdAt: "2026-07-01T10:05:00.000Z",
  },
  {
    name: "Venkat center",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "prospect",
    reason:
      "didnot pick the call. sent message via linkedin. She asked the purpose for calling and cut the call afyer that - Please contact by friday 11am",
    createdAt: "2026-07-01T10:10:00.000Z",
  },
  {
    name: "RMKV Silks",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "July 2026",
    status: "prospect",
    reason: "will go though your deck and will let you know",
    createdAt: "2026-07-01T10:15:00.000Z",
  },
  {
    name: "Basics Llife",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "July 2026",
    status: "rejected",
    reason:
      "Speaking with someone else thank you so much I dont require a saas platform - sent over the pitch deck",
    createdAt: "2026-07-01T10:20:00.000Z",
  },
  {
    name: "Wockharft Hospitals",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "prospect",
    reason: "not picked , call after 2 days",
    createdAt: "2026-07-01T10:25:00.000Z",
  },
  {
    name: "Kangaroo Kids",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "prospect",
    reason: "not picked , call after 2 days",
    createdAt: "2026-07-01T10:30:00.000Z",
  },
  {
    name: "Gleneagles",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "July 2026",
    status: "prospect",
    reason: "not picked , call after 2 days",
    createdAt: "2026-07-01T10:35:00.000Z",
  },
  {
    name: "Blissclub",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "July 2026",
    status: "prospect",
    reason: "not picked , call after 2 days",
    createdAt: "2026-07-01T10:40:00.000Z",
  },
  {
    name: "Tasva",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "July 2026",
    status: "prospect",
    reason: "not picked , call after 2 days",
    createdAt: "2026-07-01T10:45:00.000Z",
  },
  {
    name: "Sparsh Hospital",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "June 2026",
    status: "prospect",
    reason:
      "visited website - spoke with srinivas he said the only way to connect is through mail with nawaz - sent followup mail to nawaz",
    createdAt: "2026-06-30T10:00:00.000Z",
  },
  {
    name: "Indira IVF",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "June 2026",
    status: "demo",
    reason: "Prasoontomar meeting booked at 6.30 pm - 9044433270",
    createdAt: "2026-06-30T10:05:00.000Z",
  },
  {
    name: "Narayana Health",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "June 2026",
    status: "prospect",
    reason:
      "Ashutosh - 8422912155- called but did not speak - udit singh-9874573737 - we can connect on monday , will condirm availability thorugh whatsapp",
    createdAt: "2026-06-30T10:10:00.000Z",
  },
  {
    name: "Sakhiya Skin Clinic",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "June 2026",
    status: "prospect",
    reason: "did not pick the call, need to call back later",
    createdAt: "2026-06-30T10:15:00.000Z",
  },
  {
    name: "Cloudnine",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "June 2026",
    status: "prospect",
    reason: "called but no response, will try calling again after some time",
    createdAt: "2026-06-30T10:20:00.000Z",
  },
  {
    name: "Yatharth Hospitals",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "June 2026",
    status: "prospect",
    reason: "did not answer, follow up later in the day",
    createdAt: "2026-06-30T10:25:00.000Z",
  },
  {
    name: "Dava India Pharmacy",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "June 2026",
    status: "prospect",
    reason: "no response, call back after some time",
    createdAt: "2026-06-30T10:30:00.000Z",
  },
  {
    name: "Enamor",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "June 2026",
    status: "prospect",
    reason: "did not pick up the call, try connecting later",
    createdAt: "2026-06-30T10:35:00.000Z",
  },
  {
    name: "Zivame",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "June 2026",
    status: "prospect",
    reason: "call went unanswered, need to connect later",
    createdAt: "2026-06-30T10:40:00.000Z",
  },
  {
    name: "Neerus",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "June 2026",
    status: "prospect",
    reason: "did not pick up, call back after some time",
    createdAt: "2026-06-30T10:45:00.000Z",
  },
  {
    name: "Kankatala",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "June 2026",
    status: "prospect",
    reason: "no reply on the call, will retry after a short interval",
    createdAt: "2026-06-30T10:50:00.000Z",
  },
  {
    name: "Aster Medcity",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "June 2026",
    status: "prospect",
    reason:
      "followup message sent on whatsapp - he said will get back to you - Muhammad HOM 9809001690",
    createdAt: "2026-06-29T10:00:00.000Z",
  },
  {
    name: "Havells India Private Ltd",
    owner: "Bhuvaneshwari",
    industry: "Electronics Retail",
    month: "June 2026",
    status: "prospect",
    reason: "will call you back whenever I find time - Abhijeet DGM - 9632191287",
    createdAt: "2026-06-29T10:00:00.000Z",
  },
  {
    name: "Geetham Veg Restaurant",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "prospect",
    reason:
      "Follow message on whatsapp sent asking the update on pre recorded video sent earlier - did not pick my call - he himself called back again and cut the call after intro - Muthukumar - 9142000500",
    createdAt: "2026-06-29T10:00:00.000Z",
  },
  {
    name: "Zudio",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "June 2026",
    status: "rejected",
    reason:
      "Udayam 9029009916- Marketing Lead - no we are not looking for any product - sent pitch deck",
    createdAt: "2026-06-29T10:00:00.000Z",
  },
  {
    name: "Manyavar",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "June 2026",
    status: "prospect",
    reason:
      "Jagadeesh Mng Partner 941032524- did not pick up , sent message on whatsapp , linkedin",
    createdAt: "2026-06-29T10:00:00.000Z",
  },
  {
    name: "Soch Apparels",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "June 2026",
    status: "prospect",
    reason: "Srijita - Call back next week sent message over whatsapp",
    createdAt: "2026-06-29T10:00:00.000Z",
  },
  {
    name: "Indira IVF Fertility",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "June 2026",
    status: "prospect",
    reason: "Nobody picked the call",
    createdAt: "2026-06-29T10:00:00.000Z",
  },
  {
    name: "Paragon Restaurant",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "prospect",
    reason:
      "whatsapp followup message sent - Ratheesh told to call diljit - 9645311333 diljit - did not pick the call",
    createdAt: "2026-06-25T10:00:00.000Z",
  },
  {
    name: "KUN exclusive",
    owner: "Bhuvaneshwari",
    industry: "Automotive",
    month: "June 2026",
    status: "prospect",
    reason: "did not pick the call",
    createdAt: "2026-06-25T10:00:00.000Z",
  },
  {
    name: "Guntur Gourmet",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "prospect",
    reason: "said will share their marketing team contact via whatsapp - but did not reply",
    createdAt: "2026-06-25T10:00:00.000Z",
  },
  {
    name: "Havells",
    owner: "Bhuvaneshwari",
    industry: "Electronics Retail",
    month: "June 2026",
    status: "prospect",
    reason: "call back on monday",
    createdAt: "2026-06-25T10:00:00.000Z",
  },
  {
    name: "Aster Medcity",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "June 2026",
    status: "prospect",
    reason: "please remind on monday",
    createdAt: "2026-06-25T10:00:00.000Z",
  },
  {
    name: "Palamuru Grill",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "prospect",
    reason:
      "called madhapur branch and they told to call after 30 minutes - 8712990029 - picked but did not responded and cut",
    createdAt: "2026-06-25T10:00:00.000Z",
  },
  {
    name: "Altigreen",
    owner: "Bhuvaneshwari",
    industry: "Automotive",
    month: "June 2026",
    status: "prospect",
    reason: "lokesha- 9964948544 - Assistant Manager - will call back later",
    createdAt: "2026-06-25T10:00:00.000Z",
  },
  {
    name: "Roush",
    owner: "Bhuvaneshwari",
    industry: "Other",
    month: "June 2026",
    status: "rejected",
    reason: "Might not fit their needs",
    createdAt: "2026-06-25T10:00:00.000Z",
  },
  {
    name: "california burrito",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "demo",
    reason: "Demo completed to kamsa",
    createdAt: "2026-06-24T10:00:00.000Z",
  },
  {
    name: "Aster Medcity",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "June 2026",
    status: "prospect",
    reason: "Share deck through whatsapp to muhammad - 9809001690 - pitch deck shared",
    createdAt: "2026-06-24T10:00:00.000Z",
  },
  {
    name: "Geetham",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "prospect",
    reason: "Prerecorded video sent",
    createdAt: "2026-06-24T10:00:00.000Z",
  },
  {
    name: "Cascad",
    owner: "Bhuvaneshwari",
    industry: "Other",
    month: "June 2026",
    status: "prospect",
    reason: "Pre recorded video sent",
    createdAt: "2026-06-24T10:00:00.000Z",
  },
  {
    name: "Adinn Advertising",
    owner: "Bhuvaneshwari",
    industry: "Digital Marketing",
    month: "April 2026",
    status: "prospect",
    reason: "Follow up",
  },
  {
    name: "AGR / Arabian Garden",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "April 2026",
    status: "rejected",
    reason:
      "Did not pick initially, later said product not required and they focus on outdoor marketing",
  },
  {
    name: "Ajfan",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "April 2026",
    status: "prospect",
    reason: "Follow up",
  },
  {
    name: "ARAMYA",
    owner: "Om Prakash",
    industry: "Other",
    month: "April 2026",
    status: "prospect",
    reason: "Asked to share proposal via email",
  },
  {
    name: "Aravind IVF",
    owner: "Om Prakash",
    industry: "Healthcare",
    month: "April 2026",
    status: "rejected",
    reason: "Managing through GMB dashboard",
  },
  {
    name: "Arvind Fashion Limited",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "April 2026",
    status: "prospect",
    reason: "Shared pitch deck through WhatsApp",
  },
  {
    name: "AVR Swarna Mahal",
    owner: "Bhuvaneshwari",
    industry: "Jewellery Retail",
    month: "April 2026",
    status: "prospect",
    reason: "Follow up pending",
  },
  {
    name: "Bajaj Electronics",
    owner: "Om Prakash",
    industry: "Electronics Retail",
    month: "April 2026",
    status: "prospect",
    reason: "Using multiple tools, team may try trial version",
  },
  {
    name: "Banana Club",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "April 2026",
    status: "prospect",
    reason: "Travelling, will get back later",
  },
  {
    name: "Big Scoop Cafe",
    owner: "Om Prakash",
    industry: "Food & Beverage",
    month: "April 2026",
    status: "prospect",
    reason: "Will get back if required in future",
  },
  {
    name: "Cafe Coffee Day",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "April 2026",
    status: "prospect",
    reason: "PPT shared through email",
  },
  {
    name: "Chai Kaapi",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "April 2026",
    status: "prospect",
    reason: "Shared deck over LinkedIn",
  },
  {
    name: "Chennai Mobiles",
    owner: "Venkat",
    industry: "Electronics Retail",
    month: "April 2026",
    status: "rejected",
    reason: "No requirement for now",
  },
  {
    name: "COCO TANG",
    owner: "Om Prakash",
    industry: "Food & Beverage",
    month: "April 2026",
    status: "rejected",
    reason: "No requirement currently due to tourism location",
  },
  {
    name: "Cookieman",
    owner: "Venkat",
    industry: "Food & Beverage",
    month: "April 2026",
    status: "demo",
    reason: "Demo Completed",
  },
  {
    name: "Cream Stone",
    owner: "Venkat",
    industry: "Food & Beverage",
    month: "April 2026",
    status: "prospect",
    reason: "PPT not shared, will get back if required",
  },
  {
    name: "Curefit",
    owner: "Bhuvaneshwari",
    industry: "Fitness & Wellness",
    month: "April 2026",
    status: "prospect",
    reason: "Follow up",
  },
  {
    name: "Damro Furniture",
    owner: "Om Prakash",
    industry: "Furniture Retail",
    month: "April 2026",
    status: "rejected",
    reason: "Franchisees manage stores",
  },
  {
    name: "Derbymen",
    owner: "Om Prakash",
    industry: "Apparel & Footwear",
    month: "April 2026",
    status: "rejected",
    reason: "Not interested",
  },
  {
    name: "Edify Education - Rajesh Kumar",
    owner: "Om Prakash",
    industry: "Education",
    month: "April 2026",
    status: "rejected",
    reason: "Number does not exist",
  },
  {
    name: "Edify Education - Dr. Aditi Singh Thakur",
    owner: "Om Prakash",
    industry: "Education",
    month: "April 2026",
    status: "prospect",
    reason: "Did not pick",
  },
  {
    name: "Educadd Learning Solutions",
    owner: "Om Prakash",
    industry: "Education",
    month: "April 2026",
    status: "prospect",
    reason: "Busy with admissions, follow up later",
  },
  {
    name: "FIGAROS'S PIZZA",
    owner: "Om Prakash",
    industry: "Food & Beverage",
    month: "April 2026",
    status: "prospect",
    reason: "Call on Wednesday 3 PM",
  },
  {
    name: "First Cry",
    owner: "Bhuvaneshwari",
    industry: "Retail (General)",
    month: "April 2026",
    status: "prospect",
    reason: "Email sent",
  },
  {
    name: "Girias",
    owner: "Bhuvaneshwari",
    industry: "Electronics Retail",
    month: "April 2026",
    status: "prospect",
    reason: "Find the right contact",
  },
  {
    name: "HALF BILLION DOLLAR VENTURES",
    owner: "Om Prakash",
    industry: "Other",
    month: "April 2026",
    status: "prospect",
    reason: "Call after 5 PM, later did not pick",
  },
  {
    name: "Hatsun",
    owner: "Om Prakash",
    industry: "Food Processing",
    month: "April 2026",
    status: "rejected",
    reason: "Using Promanage",
  },
  {
    name: "Hatti Kaapi",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "April 2026",
    status: "prospect",
    reason: "Shared pricing and pitch deck through WhatsApp",
  },
  {
    name: "HazelNut Factory",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "April 2026",
    status: "prospect",
    reason: "Shared PPT, follow up needed",
  },
  {
    name: "House of Rare",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "April 2026",
    status: "prospect",
    reason: "Shared PPT over LinkedIn",
  },
  {
    name: "IGO AGRITECHFARMS",
    owner: "Om Prakash",
    industry: "Other",
    month: "April 2026",
    status: "prospect",
    reason: "Messaged on LinkedIn",
  },
  {
    name: "Indian Terrain",
    owner: "Om Prakash",
    industry: "Apparel & Footwear",
    month: "April 2026",
    status: "prospect",
    reason: "Asked to call after 3 PM, later did not pick",
  },
  {
    name: "Indira IVF Fertility Centre",
    owner: "Om Prakash",
    industry: "Healthcare",
    month: "April 2026",
    status: "prospect",
    reason: "Follow up at 5 PM",
  },
  {
    name: "KAG",
    owner: "Bhuvaneshwari",
    industry: "Other",
    month: "April 2026",
    status: "prospect",
    reason: "Not the right contact, others unavailable",
  },
  {
    name: "Kaya Skin Clinic",
    owner: "Om Prakash",
    industry: "Beauty & Wellness",
    month: "April 2026",
    status: "prospect",
    reason: "No update",
  },
  {
    name: "Kun Motor Company",
    owner: "Om Prakash",
    industry: "Automotive",
    month: "April 2026",
    status: "prospect",
    reason: "Contract",
  },
  {
    name: "Kushals",
    owner: "Bhuvaneshwari",
    industry: "Jewellery Retail",
    month: "April 2026",
    status: "demo",
    reason: "Demo Completed",
  },
  {
    name: "Lalitha Jewellery",
    owner: "Om Prakash",
    industry: "Jewellery Retail",
    month: "April 2026",
    status: "prospect",
    reason: "Warm lead, possible demo in May",
  },
  {
    name: "Manipal Health / Hospitals",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "April 2026",
    status: "prospect",
    reason: "Asked to call tomorrow at 10 AM, follow up pending",
  },
  {
    name: "Maple Bear - Gaurav Sharma",
    owner: "Om Prakash",
    industry: "Education",
    month: "April 2026",
    status: "prospect",
    reason: "Occupied",
  },
  {
    name: "Maple Bear - Anuj Bhatia",
    owner: "Om Prakash",
    industry: "Education",
    month: "April 2026",
    status: "prospect",
    reason: "Asked to share proposal and follow up Monday",
  },
  {
    name: "Maple Bear - Priya Bisht",
    owner: "Om Prakash",
    industry: "Education",
    month: "April 2026",
    status: "prospect",
    reason: "Switched off",
  },
  {
    name: "Mc Kingstown",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "April 2026",
    status: "prospect",
    reason: "PPT not shared, will get back if required",
  },
  {
    name: "Mera Laundry",
    owner: "Om Prakash",
    industry: "Laundry Services",
    month: "April 2026",
    status: "rejected",
    reason: "Not interested",
  },
  {
    name: "Minister White",
    owner: "Venkat",
    industry: "Apparel & Footwear",
    month: "April 2026",
    status: "demo",
    reason: "Demo Completed",
  },
  {
    name: "Motilal Oswal",
    owner: "Bhuvaneshwari",
    industry: "Financial Services",
    month: "April 2026",
    status: "prospect",
    reason: "Find the right contact",
  },
  {
    name: "Mr Blue",
    owner: "Om Prakash",
    industry: "Laundry Services",
    month: "April 2026",
    status: "rejected",
    reason: "No requirement for current business scale",
  },
  {
    name: "Nexa Kalyani",
    owner: "Om Prakash",
    industry: "Automotive",
    month: "April 2026",
    status: "rejected",
    reason: "Marketing handled by head team",
  },
  {
    name: "Oliva Skin & Hair Clinic",
    owner: "Om Prakash",
    industry: "Beauty & Wellness",
    month: "April 2026",
    status: "prospect",
    reason: "Interested, follow up after 2 weeks",
  },
  {
    name: "Pai International Electronics",
    owner: "Om Prakash",
    industry: "Electronics Retail",
    month: "April 2026",
    status: "prospect",
    reason: "Follow up after summer",
  },
  {
    name: "Paragon",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "April 2026",
    status: "prospect",
    reason: "Follow up",
  },
  {
    name: "Paulsons Group",
    owner: "Venkat",
    industry: "Food & Beverage",
    month: "April 2026",
    status: "rejected",
    reason: "Franchise owners manage stores individually",
  },
  {
    name: "Polar Bear",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "April 2026",
    status: "prospect",
    reason: "Follow up",
  },
  {
    name: "Poorvika",
    owner: "Om Prakash",
    industry: "Electronics Retail",
    month: "April 2026",
    status: "prospect",
    reason: "Contact Sudhir after 2 PM on 29.04.2026",
  },
  {
    name: "Popees",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "April 2026",
    status: "demo",
    reason: "Demo Completed",
  },
  {
    name: "Prisma",
    owner: "Bhuvaneshwari",
    industry: "Digital/Advertising",
    month: "April 2026",
    status: "prospect",
    reason: "Check for right contact",
  },
  {
    name: "Rainbow Hospital",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "April 2026",
    status: "prospect",
    reason: "Follow up",
  },
  {
    name: "Ramraj Cotton",
    owner: "Om Prakash",
    industry: "Apparel & Footwear",
    month: "April 2026",
    status: "rejected",
    reason: "Using another product/tool",
  },
  {
    name: "Royal Enfield",
    owner: "Bhuvaneshwari",
    industry: "Automotive",
    month: "April 2026",
    status: "demo",
    reason: "Demo Completed",
  },
  {
    name: "Sai Silks Kalamandir",
    owner: "Venkat",
    industry: "Apparel & Footwear",
    month: "April 2026",
    status: "prospect",
    reason: "Shared email",
  },
  {
    name: "Sakhiya Skin Clinic",
    owner: "Om Prakash",
    industry: "Beauty & Wellness",
    month: "April 2026",
    status: "prospect",
    reason: "No update",
  },
  {
    name: "SANFORT WORLD GLOBAL",
    owner: "Om Prakash",
    industry: "Education",
    month: "April 2026",
    status: "prospect",
    reason: "Did not pick",
  },
  {
    name: "Sangeetha Mobiles",
    owner: "Om Prakash",
    industry: "Electronics Retail",
    month: "April 2026",
    status: "prospect",
    reason: "Not responding",
  },
  {
    name: "Siyaram",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "April 2026",
    status: "rejected",
    reason: "Did not pick, no current requirement",
  },
  {
    name: "Soch Apparels",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "April 2026",
    status: "prospect",
    reason: "Sent pitch deck, follow up pending",
  },
  {
    name: "Souled Store",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "April 2026",
    status: "prospect",
    reason: "Did not pick the call",
  },
  {
    name: "Style Spa Furniture Ltd",
    owner: "Om Prakash",
    industry: "Furniture Retail",
    month: "April 2026",
    status: "rejected",
    reason: "Already using another tool",
  },
  {
    name: "Surya Nissan and Datsun Car",
    owner: "Om Prakash",
    industry: "Automotive",
    month: "April 2026",
    status: "prospect",
    reason: "Contract",
  },
  {
    name: "Technosport",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "April 2026",
    status: "prospect",
    reason: "Shared responsible department contact",
  },
  {
    name: "Thangamayil Jewellery",
    owner: "Bhuvaneshwari",
    industry: "Jewellery Retail",
    month: "April 2026",
    status: "demo",
    reason: "Demo Completed",
  },
  {
    name: "THE COFFEE EVOLUTION",
    owner: "Om Prakash",
    industry: "Food & Beverage",
    month: "April 2026",
    status: "prospect",
    reason: "Marketing team will reach out",
  },
  {
    name: "TTK Prestige",
    owner: "Bhuvaneshwari",
    industry: "Retail (General)",
    month: "April 2026",
    status: "demo",
    reason: "Demo Completed",
  },
  {
    name: "Veranda RACE",
    owner: "Bhuvaneshwari",
    industry: "Education",
    month: "April 2026",
    status: "prospect",
    reason: "Connected through LinkedIn",
  },
  {
    name: "Viveks",
    owner: "Om Prakash",
    industry: "Electronics Retail",
    month: "April 2026",
    status: "rejected",
    reason: "Already using another tool",
  },
  {
    name: "Vmart",
    owner: "Om Prakash",
    industry: "Supermarket & Grocery",
    month: "April 2026",
    status: "rejected",
    reason: "Call not continuing",
  },
  {
    name: "WASH GUYS",
    owner: "Om Prakash",
    industry: "Laundry Services",
    month: "April 2026",
    status: "prospect",
    reason: "Call back scheduled at 12 PM",
  },
  {
    name: "Wrogn",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "April 2026",
    status: "prospect",
    reason: "Shared pitch deck through WhatsApp",
  },
  {
    name: "Dr. Smilez Dental Group",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "April 2026",
    status: "demo",
    reason: "Demo Completed",
  },
  {
    name: "Kongsi Tea Bar",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "April 2026",
    status: "demo",
    reason: "Demo Completed",
  },
  {
    name: "KIMS Hospital",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "April 2026",
    status: "demo",
    reason: "Demo Completed",
  },
  {
    name: "Rainbow Hospital",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Follow up",
  },
  {
    name: "Girias",
    owner: "Bhuvaneshwari",
    industry: "Electronics Retail",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Find the right contact",
  },
  {
    name: "Curefit",
    owner: "Bhuvaneshwari",
    industry: "Fitness & Wellness",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Follow up",
  },
  {
    name: "Hatti Kaapi",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Sent the pitch deck through WA",
  },
  {
    name: "Adinn Advertising",
    owner: "Bhuvaneshwari",
    industry: "Digital Marketing",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Follow up",
  },
  {
    name: "Prisma",
    owner: "Bhuvaneshwari",
    industry: "Digital/Advertising",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Check for right contact",
  },
  {
    name: "Popees",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Follow up",
  },
  {
    name: "TTK Prestige",
    owner: "Bhuvaneshwari",
    industry: "Retail (General)",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Follow up",
  },
  {
    name: "First Cry",
    owner: "Bhuvaneshwari",
    industry: "Retail (General)",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Email sent",
  },
  {
    name: "Arabian Garden",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Call after election",
  },
  {
    name: "Sai Silks Kalamandir",
    owner: "Venkat",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Shared Email",
  },
  {
    name: "AVR Swarna Mahal",
    owner: "Bhuvaneshwari",
    industry: "Jewellery Retail",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Follow Up",
  },
  {
    name: "Cream Stone",
    owner: "Venkat",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "PPT Not shared, Will get back if required.",
  },
  {
    name: "Royal Enfield",
    owner: "Bhuvaneshwari",
    industry: "Automotive",
    month: "Feb to March 2026",
    status: "demo",
    reason: "Demo Completed",
  },
  {
    name: "House of Rare",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Shared PPT over LinkedIn",
  },
  {
    name: "Ethnix by Reymand",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "rejected",
    reason: "Using another product",
  },
  {
    name: "Ramraj Cotton",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "rejected",
    reason: "Using another product",
  },
  {
    name: "Derbymen",
    owner: "Aswini",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Not started anything",
  },
  {
    name: "Technosport",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Check for right contact",
  },
  {
    name: "5k Care Car",
    owner: "Aswini",
    industry: "Automotive Services",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Vcare",
    owner: "Bhuvaneshwari",
    industry: "Beauty & Wellness",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Health & Glow",
    owner: "Bhuvaneshwari",
    industry: "Beauty & Wellness",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Marie Claire",
    owner: "Aswini",
    industry: "Beauty & Wellness",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "The Building Doctor",
    owner: "Aswini",
    industry: "Construction",
    month: "Feb to March 2026",
    status: "demo",
  },
  {
    name: "The Building Doctor",
    owner: "Aswini",
    industry: "Construction",
    month: "April 2026",
    status: "trial",
  },
  {
    name: "Digitmarket",
    owner: "Aswini",
    industry: "Digital Marketing",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Woodhead",
    owner: "Aswini",
    industry: "Digital Marketing",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Metamorphisi Preschool",
    owner: "Aswini",
    industry: "Education",
    month: "Feb to March 2026",
    status: "demo",
    reason: "Follow up for onboarding",
  },
  {
    name: "Veranda RACE",
    owner: "Bhuvaneshwari",
    industry: "Education",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "CADD Centre",
    owner: "Bhuvaneshwari",
    industry: "Education",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "IRIS Florets",
    owner: "Aswini",
    industry: "Education",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Sathya",
    owner: "Bhuvaneshwari",
    industry: "Electronics Retail",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Viveks",
    owner: "Bhuvaneshwari",
    industry: "Electronics Retail",
    month: "Feb to March 2026",
    status: "rejected",
    reason: "Already using another tool",
  },
  {
    name: "Snitch",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "My Cash Easy",
    owner: "Aswini",
    industry: "Financial Services",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Cothas Coffee",
    owner: "Venkat",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "demo",
    reason: "Occupied. Reconnect on 10th for onboarding",
  },
  {
    name: "The Falooda",
    owner: "Aswini",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Food Mohalla",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "rejected",
    reason: "Not interested",
  },
  {
    name: "Bombay Kulfi",
    owner: "Aswini",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "demo",
  },
  {
    name: "Aaladipattiyan",
    owner: "Venkat",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "A2B",
    owner: "Venkat",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Haldiram's",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Mr Sandwich",
    owner: "Aswini",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Chai Kaapi",
    owner: "Aswini",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Frozen Bottle",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "rejected",
    reason: "Having separate agency",
  },
  {
    name: "Anjappar Chettinad",
    owner: "Aswini",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "demo",
    reason: "Using competitors product - Famepilot. Connect on Whatsapp",
  },
  {
    name: "Franks Hot Dogs",
    owner: "Aswini",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Arbain Sea Food",
    owner: "Aswini",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Polar Bear",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Follow Up",
  },
  {
    name: "COCO TANG",
    owner: "Aswini",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Cookieman",
    owner: "Venkat",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "demo",
    reason: "Demo Completed, will get back if any requirement",
  },
  {
    name: "Smoothie Factory",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Cafe Coffee Day",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "rejected",
    reason: "PPT shared over email",
  },
  {
    name: "Suto Cafe",
    owner: "Aswini",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Sent the proposal to her whatsapp, follow up pending",
  },
  {
    name: "Barbeque Nation",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Burgerman",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Uncle Peter's Pancakes",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Paragon",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Follow up",
  },
  {
    name: "Topi Vappa Biriyani",
    owner: "Aswini",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Ajfan",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Follow Up",
  },
  {
    name: "Suguna Foods Private Limited",
    owner: "Bhuvaneshwari",
    industry: "Food Processing",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Royaloak",
    owner: "Bhuvaneshwari",
    industry: "Furniture Retail",
    month: "Feb to March 2026",
    status: "rejected",
    reason: "Using Another product",
  },
  {
    name: "Aarthi Scans & Labs",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Dr. Agarwals",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Nueberg",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "Feb to March 2026",
    status: "rejected",
    reason: "Using another product",
  },
  {
    name: "Aravind IVF",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Clove Dental",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "Feb to March 2026",
    status: "rejected",
    reason: "Internal Management",
  },
  {
    name: "Neemrana Hotels Pvt Ltd",
    owner: "Bhuvaneshwari",
    industry: "Hospitality",
    month: "Feb to March 2026",
    status: "rejected",
    reason: "Not interested",
  },
  {
    name: "Bhima Gold",
    owner: "Bhuvaneshwari",
    industry: "Jewellery Retail",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "UClean",
    owner: "Aswini",
    industry: "Laundry Services",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "La Lavanderia",
    owner: "Aswini",
    industry: "Laundry Services",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Laundry To",
    owner: "Aswini",
    industry: "Laundry Services",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Dhobilite Laundry",
    owner: "Aswini",
    industry: "Laundry Services",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Specsmakers",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "Feb to March 2026",
    status: "rejected",
    reason: "Using another product",
  },
  {
    name: "Med Plus",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Poppees Baby Care",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Follow up",
  },
  {
    name: "Mr Blue",
    owner: "Aswini",
    industry: "Laundry Services",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Presto",
    owner: "Bhuvaneshwari",
    industry: "Retail (General)",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "KPN Fresh",
    owner: "Venkat",
    industry: "Retail (General)",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Darling Retail",
    owner: "Bhuvaneshwari",
    industry: "Retail (General)",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Born Babies",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Wrogn",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Shared the pitch deck through WA",
  },
  {
    name: "Indian Terrain",
    owner: "Aswini",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Call after 3pm",
  },
  {
    name: "Odyssey India Ltd.",
    owner: "Aswini",
    industry: "Retail (General)",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Chennai Mobiles",
    owner: "Venkat",
    industry: "Electronics Retail",
    month: "Feb to March 2026",
    status: "rejected",
    reason: "No need for now",
  },
  {
    name: "Westside",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Grocery 4 U Retail",
    owner: "Aswini",
    industry: "Supermarket & Grocery",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Kushal's Fashion Jewellery",
    owner: "Bhuvaneshwari",
    industry: "Jewellery Retail",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Puma",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Spar",
    owner: "Bhuvaneshwari",
    industry: "Supermarket & Grocery",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Zudio",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Laundrex",
    owner: "Bhuvaneshwari",
    industry: "Laundry Services",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Pick My Laundry",
    owner: "Aswini",
    industry: "Laundry Services",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Green Trends",
    owner: "Aswini",
    industry: "Beauty & Wellness",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "GRT Jewellery",
    owner: "Bhuvaneshwari",
    industry: "Jewellery Retail",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Chai Kaapi",
    owner: "Aswini",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Max Fashion India",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Pantaloons",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Zivame",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Cheese and Co",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Croma",
    owner: "Aswini",
    industry: "Electronics Retail",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Not started anything",
  },
  {
    name: "Lifestyle Stores - Easy Buy",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Licious",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Kongsi Tea Bar",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "trial",
  },
  {
    name: "Thangamayil Jewellery",
    owner: "Bhuvaneshwari",
    industry: "Jewellery Retail",
    month: "Feb to March 2026",
    status: "demo",
  },
  {
    name: "Boba Bhai",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "rejected",
    reason: "Not needed right now",
  },
  {
    name: "Palmonas",
    owner: "Bhuvaneshwari",
    industry: "Jewellery Retail",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Mc Kingstown",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "PPT not shared, will get back if required",
  },
  {
    name: "Hazel Nut Factory",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Shared the ppt, need to follow up",
  },
  {
    name: "Naadbramha Idli",
    owner: "Aswini",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Rare Rabbit",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Shared ppt over LinkedIn",
  },
  {
    name: "Madras Coffee House",
    owner: "Aswini",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Kalyan Jewellers",
    owner: "Aswini",
    industry: "Jewellery Retail",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Titan Eyeplus",
    owner: "Aswini",
    industry: "Healthcare",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Fabindia",
    owner: "Aswini",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Joyalukkas",
    owner: "Aswini",
    industry: "Jewellery Retail",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Dindigul Thalappakatti Restaurant",
    owner: "Aswini",
    industry: "Food & Beverage",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Sent the proposal to his whatsapp, cold called him",
  },
  {
    name: "Anytime Fitness",
    owner: "Aswini",
    industry: "Beauty & Wellness",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Edify Education",
    owner: "Aswini",
    industry: "Education",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Did not pick",
  },
  {
    name: "Minister White",
    owner: "Venkat",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "demo",
    reason: "Demo Completed, need to follow up",
  },
  {
    name: "i Tooth Dental Clinic",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Maybell",
    owner: "Bhuvaneshwari",
    industry: "Beauty & Wellness",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Alldone Laundromat & Dry Cleaning",
    owner: "Aswini",
    industry: "Laundry Services",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "TIME4education",
    owner: "Aswini",
    industry: "Education",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Mera Laundry",
    owner: "Aswini",
    industry: "Laundry Services",
    month: "Feb to March 2026",
    status: "demo",
    reason: "Sent Whatsapp message to him for onboarding",
  },
  {
    name: "FABO",
    owner: "Aswini",
    industry: "Laundry Services",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Dr. Smilez Dental Group",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "Feb to March 2026",
    status: "demo",
  },
  {
    name: "Damro Furniture",
    owner: "Aswini",
    industry: "Furniture Retail",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Banana Club",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Wildcraft",
    owner: "Aswini",
    industry: "Apparel & Footwear",
    month: "Feb to March 2026",
    status: "prospect",
    reason: "Sent the proposal to email id",
  },
  {
    name: "Sangeetha Mobile",
    owner: "Aswini",
    industry: "Electronics Retail",
    month: "Feb to March 2026",
    status: "prospect",
  },
  {
    name: "Mr.DIY",
    owner: "Aswini",
    industry: "Retail (General)",
    month: "Feb to March 2026",
    status: "demo",
    reason: "Demo done, he said he doesn't know us",
  },
];

const newDataRaw = [
  {
    name: "KIMS Hospital",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "May 2026",
    status: "prospect",
    reason: "Today he has appointment, so follow up after 12pm tom. to check for demo",
    createdAt: "2026-05-04T12:00:00.000Z",
  },
  {
    name: "Soch Apparels",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "May 2026",
    status: "prospect",
    reason: "Call after some time",
    createdAt: "2026-05-04T12:00:00.000Z",
  },
  {
    name: "Alldone Laundromat & Dry Cleaning",
    owner: "Om Prakash",
    industry: "Laundromat",
    month: "May 2026",
    status: "prospect",
    reason: "Need to follow back on thursday",
    createdAt: "2026-05-04T12:00:00.000Z",
  },
  {
    name: "Dhobilite Laundry",
    owner: "Om Prakash",
    industry: "Laundromat",
    month: "May 2026",
    status: "rejected",
    reason: "Not interested",
    createdAt: "2026-05-04T12:00:00.000Z",
  },
  {
    name: "Landmark Cars",
    owner: "Om Prakash",
    industry: "Automotive",
    month: "May 2026",
    status: "prospect",
    reason:
      "Abhishek Iyer Head Of Marketing Communications - He said they have enough man power , but he might convert if we pitch again",
    createdAt: "2026-05-04T12:00:00.000Z",
  },
  {
    name: "Nandhi Toyota",
    owner: "Om Prakash",
    industry: "Automotive",
    month: "May 2026",
    status: "prospect",
    reason:
      "Sri Harsha Vijayakumar - CORPORATE SALES TERRITORY HEAD - They asked for our website  , they will get back to us within 2 or 3 weeks",
    createdAt: "2026-05-04T12:00:00.000Z",
  },
  {
    name: "Kauvery Hospital",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "May 2026",
    status: "prospect",
    reason: "Follow up made",
    createdAt: "2026-05-05T12:00:00.000Z",
  },
  {
    name: "Khazana Jewellery",
    owner: "Bhuvaneshwari",
    industry: "Jewellery",
    month: "May 2026",
    status: "prospect",
    reason:
      "Shared pitch deck through mail id, follow up after 2 days (they already have tools for all the activities)",
    createdAt: "2026-05-05T12:00:00.000Z",
  },
  {
    name: "TTK Prestige",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "May 2026",
    status: "prospect",
    reason: "Make a follow up call after demo - Did not pick the call",
    createdAt: "2026-05-05T12:00:00.000Z",
  },
  {
    name: "Popees",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "May 2026",
    status: "prospect",
    reason: "He is in a meeting, call back later",
    createdAt: "2026-05-05T12:00:00.000Z",
  },
  {
    name: "Trident Auto",
    owner: "Om Prakash",
    industry: "Automotive",
    month: "May 2026",
    status: "rejected",
    reason: "Not Interested",
    createdAt: "2026-05-05T12:00:00.000Z",
  },
  {
    name: "Ola Electric",
    owner: "Om Prakash",
    industry: "Automotive",
    month: "May 2026",
    status: "rejected",
    reason: "Not Interested",
    createdAt: "2026-05-05T12:00:00.000Z",
  },
  {
    name: "Ather Space",
    owner: "Om Prakash",
    industry: "Automotive",
    month: "May 2026",
    status: "rejected",
    reason: "Not Interested",
    createdAt: "2026-05-05T12:00:00.000Z",
  },
  {
    name: "Technosport",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "May 2026",
    status: "rejected",
    reason: "He tried our product through our website, they did not like our dashboard",
    createdAt: "2026-05-05T12:00:00.000Z",
  },
  {
    name: "KIMS Hospital",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "May 2026",
    status: "prospect",
    reason: "Since there were issues in connecting could not conduct the demo meeting.",
    createdAt: "2026-05-05T12:00:00.000Z",
  },
  {
    name: "Hatti Kaapi",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "May 2026",
    status: "prospect",
    reason: "Follow Up Made",
    createdAt: "2026-05-05T12:00:00.000Z",
  },
  {
    name: "TTK Prestige",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "May 2026",
    status: "prospect",
    reason:
      "Sent Follow up email. (Mr Abhishek has requested to continue any further discussion through mail only)",
    createdAt: "2026-05-06T12:00:00.000Z",
  },
  {
    name: "KAG",
    owner: "Bhuvaneshwari",
    industry: "Other",
    month: "May 2026",
    status: "prospect",
    reason: "Sent mail to info@kagindia.com as per their suggestion.",
    createdAt: "2026-05-06T12:00:00.000Z",
  },
  {
    name: "KIMS Hospital",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "May 2026",
    status: "prospect",
    reason: "Follow Up Made, He had asked me to call tom after 11 AM",
    createdAt: "2026-05-06T12:00:00.000Z",
  },
  {
    name: "RMKV Silks",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "May 2026",
    status: "prospect",
    reason: "Call back on tuesday after texting on WA",
    createdAt: "2026-05-06T12:00:00.000Z",
  },
  {
    name: "Nalli Silks",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "May 2026",
    status: "new_lead",
    reason: "Not required right now but shared the deck through mail",
    createdAt: "2026-05-06T12:00:00.000Z",
  },
  {
    name: "Chennai Silks",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "May 2026",
    status: "new_lead",
    reason: "Not a right contact",
    createdAt: "2026-05-06T12:00:00.000Z",
  },
  {
    name: "ABFRL",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "May 2026",
    status: "prospect",
    reason: "Call back on wednesday 13/05 after 2 pm",
    createdAt: "2026-05-06T12:00:00.000Z",
  },
  {
    name: "Joy Alukkas",
    owner: "Bhuvaneshwari",
    industry: "Jewellery",
    month: "May 2026",
    status: "prospect",
    reason: "Shared deck through WA",
    createdAt: "2026-05-07T12:00:00.000Z",
  },
  {
    name: "Kankatala Textiles",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "May 2026",
    status: "new_lead",
    reason: "Call after 6 pm",
    createdAt: "2026-05-07T12:00:00.000Z",
  },
  {
    name: "KIMS Hospital",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "May 2026",
    status: "demo",
    reason: "Demo Completed, need to share proposal",
    createdAt: "2026-05-07T12:00:00.000Z",
  },
  {
    name: "Big A Solutions",
    owner: "Bhuvaneshwari",
    industry: "Digital Marketing",
    month: "May 2026",
    status: "prospect",
    reason: "call back after 2 days",
    createdAt: "2026-05-07T12:00:00.000Z",
  },
  {
    name: "Jayalakshmi Textiles",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "May 2026",
    status: "new_lead",
    reason: "Did not pick the call",
    createdAt: "2026-05-07T12:00:00.000Z",
  },
  {
    name: "Neerus",
    owner: "Bhuvaneshwari",
    industry: "Other",
    month: "May 2026",
    status: "new_lead",
    reason: "Not Reachable",
    createdAt: "2026-05-07T12:00:00.000Z",
  },
  {
    name: "KIMS Hospital",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "May 2026",
    status: "proposal_sent",
    reason: "Shared the proposal via mail",
    createdAt: "2026-05-08T12:00:00.000Z",
  },
  {
    name: "Soch Apparels",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "May 2026",
    status: "prospect",
    reason: "Sent follow up message through WA",
    createdAt: "2026-05-08T12:00:00.000Z",
  },
  {
    name: "TTK Prestige",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "May 2026",
    status: "prospect",
    reason: "sent 2nd follow up mail",
    createdAt: "2026-05-08T12:00:00.000Z",
  },
  {
    name: "Popees",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "May 2026",
    status: "prospect",
    reason: "follow up email sent",
    createdAt: "2026-05-08T12:00:00.000Z",
  },
  {
    name: "TVS Motor Dealer Network",
    owner: "Bhuvaneshwari",
    industry: "Automotive",
    month: "May 2026",
    status: "rejected",
    reason: "Not Interested, They are using another platform so not needed now.",
    createdAt: "2026-05-08T12:00:00.000Z",
  },
  {
    name: "Kalyani Motors",
    owner: "Bhuvaneshwari",
    industry: "Automotive",
    month: "May 2026",
    status: "new_lead",
    reason: "Sent pitchdeck through WA",
    createdAt: "2026-05-08T12:00:00.000Z",
  },
  {
    name: "Advaith hyundai",
    owner: "Bhuvaneshwari",
    industry: "Automotive",
    month: "May 2026",
    status: "new_lead",
    reason: "Did not pick the call",
    createdAt: "2026-05-08T12:00:00.000Z",
  },
  {
    name: "Bimal Auto Agency",
    owner: "Bhuvaneshwari",
    industry: "Automotive",
    month: "May 2026",
    status: "new_lead",
    reason: "Person not working there, not picked the call",
    createdAt: "2026-05-08T12:00:00.000Z",
  },
  {
    name: "Deepsense Digital",
    owner: "Bhuvaneshwari",
    industry: "Digital Marketing",
    month: "May 2026",
    status: "new_lead",
    reason: "Shared pitchdeck with co founder",
    createdAt: "2026-05-08T12:00:00.000Z",
  },
  {
    name: "Adinn Advertising",
    owner: "Bhuvaneshwari",
    industry: "Digital Marketing",
    month: "May 2026",
    status: "new_lead",
    reason: "After May 16",
    createdAt: "2026-05-08T12:00:00.000Z",
  },
  {
    name: "Polar Bear",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "May 2026",
    status: "new_lead",
    reason: "He said to give him a week time",
    createdAt: "2026-05-08T12:00:00.000Z",
  },
  {
    name: "Arvind Fashion Limited",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "May 2026",
    status: "new_lead",
    reason: "Sent WA Reminder",
    createdAt: "2026-05-08T12:00:00.000Z",
  },
  {
    name: "snitch",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "May 2026",
    status: "prospect",
    reason: "shared deck through WA",
    createdAt: "2026-05-08T12:00:00.000Z",
  },
  {
    name: "Rainbow Hospital",
    owner: "Bhuvaneshwari",
    industry: "Other",
    month: "May 2026",
    status: "new_lead",
    reason: "Attended but no response",
    createdAt: "2026-05-11T12:00:00.000Z",
  },
  {
    name: "Deepsense Digital",
    owner: "Bhuvaneshwari",
    industry: "Digital Marketing",
    month: "May 2026",
    status: "new_lead",
    reason: "Sent WA Reminder",
    createdAt: "2026-05-11T12:00:00.000Z",
  },
  {
    name: "HCG (HealthCare Global Enterprises)",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "May 2026",
    status: "prospect",
    reason: "Call by 12pm tomorrow",
    createdAt: "2026-05-11T12:00:00.000Z",
  },
  {
    name: "Harsha Toyota",
    owner: "Om Prakash",
    industry: "Automotive",
    month: "May 2026",
    status: "demo",
    reason: "Demo completed.",
    createdAt: "2026-05-11T12:00:00.000Z",
  },
  {
    name: "HCG (HealthCare Global Enterprises)",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "May 2026",
    status: "prospect",
    reason: "Follow up call made but no response, Shared deck throguh WA with sajid",
    createdAt: "2026-05-12T12:00:00.000Z",
    followUpCount: 1,
  },
  {
    name: "Glen Eagles",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "May 2026",
    status: "new_lead",
    reason: "Shared pitch deck through WA",
    createdAt: "2026-05-12T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Partha Dental",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "May 2026",
    status: "new_lead",
    reason: "Not the right contact",
    createdAt: "2026-05-12T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Kosmoderma skin and hair",
    owner: "Bhuvaneshwari",
    industry: "Beauty & Wellness",
    month: "May 2026",
    status: "prospect",
    reason: "Fix demo for 3pm tomorrow",
    createdAt: "2026-05-12T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "DermaVue Clinics",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "May 2026",
    status: "prospect",
    reason: "He said that he will discuss with their operations team and call back if needed",
    createdAt: "2026-05-12T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "RMKV Silks",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "May 2026",
    status: "prospect",
    reason: "Shared pitch deck through mail",
    createdAt: "2026-05-12T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "KIMS (Krishna Institute)",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "May 2026",
    status: "prospect",
    reason: "Follow up call made and he need to check with his ceo",
    createdAt: "2026-05-12T12:00:00.000Z",
    followUpCount: 1,
  },
  {
    name: "Popees",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "May 2026",
    status: "prospect",
    reason: "We will contact you.",
    createdAt: "2026-05-13T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Kosmoderma skin and hair",
    owner: "Bhuvaneshwari",
    industry: "Beauty & Wellness",
    month: "May 2026",
    status: "demo",
    reason:
      "Follow up made to remind about the demo - Demo Completed - we need to give competitor analysis",
    createdAt: "2026-05-13T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Motherhood Hospitals",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "May 2026",
    status: "new_lead",
    reason: "Not required right now, shared the pitch deck through WA",
    createdAt: "2026-05-13T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Oliva Skin & Hair Clinic",
    owner: "Bhuvaneshwari",
    industry: "Beauty & Wellness",
    month: "May 2026",
    status: "demo",
    reason: "Demo by 6pm - Demo completed",
    createdAt: "2026-05-13T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Sparsh",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "May 2026",
    status: "new_lead",
    createdAt: "2026-05-26T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Oasis fertility",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "May 2026",
    status: "new_lead",
    createdAt: "2026-05-26T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Dava India Pharmacy",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "May 2026",
    status: "new_lead",
    createdAt: "2026-05-26T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Wellness Forever Medicare",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "May 2026",
    status: "new_lead",
    createdAt: "2026-05-26T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Sahyadri Hospitals",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "May 2026",
    status: "new_lead",
    createdAt: "2026-05-26T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Vecura Wellness clinic",
    owner: "Bhuvaneshwari",
    industry: "Beauty & Wellness",
    month: "May 2026",
    status: "new_lead",
    createdAt: "2026-05-26T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Dr. Batra's Homeopathy",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "May 2026",
    status: "new_lead",
    createdAt: "2026-05-26T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Redcliffe Labs",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "June 2026",
    status: "demo",
    reason: "Need one more session and he asked for the source of keyword",
    createdAt: "2026-06-02T13:43:32.966Z",
    followUpCount: 0,
  },
  {
    name: "Sri Krishna Silks",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "June 2026",
    status: "demo",
    reason: "Connect with his social media manager",
    createdAt: "2026-06-02T13:42:38.172Z",
    followUpCount: 0,
  },
  {
    name: "Sri Krishna Silks",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "June 2026",
    status: "rejected",
    reason: "Price seems bit high for them and they dont want to exploit the existing system",
    createdAt: "2026-06-16T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "California Burrito",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "prospect",
    reason: "Send product deck to kamsali via whatsapp",
    createdAt: "2026-06-16T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Shree Anandhaas Sweets and Snacks",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "prospect",
    reason: "Send email to Ravi, he said he will revert if needed",
    createdAt: "2026-06-16T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Donne Briyani",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "prospect",
    reason: "Need to follow Pradeep TK up on 18.06.2026 afternoon",
    createdAt: "2026-06-16T12:00:00.000Z",
    followUpCount: 0,
    reminderType: "followup",
    reminderDate: "2026-06-18T12:00:00.000Z",
    reminderClosed: true,
  },
  {
    name: "KPN",
    owner: "Bhuvaneshwari",
    industry: "Retail (General)",
    month: "June 2026",
    status: "rejected",
    reason:
      "Previously Srinivasan said they dont want, so i tries other two gowtham didnot picked, sahil is not working there",
    createdAt: "2026-06-16T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Cakebee",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "prospect",
    reason: "Called to the number got from website = call back on 17.06.2026",
    createdAt: "2026-06-16T12:00:00.000Z",
    followUpCount: 0,
    reminderType: "followup",
    reminderDate: "2026-06-17T12:00:00.000Z",
    reminderClosed: false,
  },
  {
    name: "Page 3",
    owner: "Bhuvaneshwari",
    industry: "Beauty & Wellness",
    month: "June 2026",
    status: "prospect",
    reason: "Revanth roy is busy",
    createdAt: "2026-06-16T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Spicy venue",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "rejected",
    reason: "We do it by 3rd party",
    createdAt: "2026-06-16T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Sterling holidays",
    owner: "Bhuvaneshwari",
    industry: "Hospitality",
    month: "June 2026",
    status: "rejected",
    reason: "He is already using promanage - sent product deck over whatsapp",
    createdAt: "2026-06-16T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Justa hotels and resorts",
    owner: "Bhuvaneshwari",
    industry: "Hospitality",
    month: "June 2026",
    status: "rejected",
    reason: "They said they no need our product",
    createdAt: "2026-06-16T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Treebo",
    owner: "Bhuvaneshwari",
    industry: "Hospitality",
    month: "June 2026",
    status: "rejected",
    reason: "We already have our own product with 50 techies working on it",
    createdAt: "2026-06-16T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Royal Orchid",
    owner: "Bhuvaneshwari",
    industry: "Hospitality",
    month: "June 2026",
    status: "rejected",
    reason: "Not interested",
    createdAt: "2026-06-16T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Evolve back",
    owner: "Bhuvaneshwari",
    industry: "Hospitality",
    month: "June 2026",
    status: "prospect",
    reason: "Email sent to nikhil.p@evolveback.com",
    createdAt: "2026-06-16T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Laundrokart",
    owner: "Bhuvaneshwari",
    industry: "Laundry Services",
    month: "June 2026",
    status: "rejected",
    reason: "Nagarjun said no need",
    createdAt: "2026-06-16T12:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Pommys",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "June 2026",
    status: "prospect",
    reason: "Did not pick",
    createdAt: "2026-06-16T12:00:00.000Z",
    followUpCount: 0,
  },

  // June 18, 2026 Updates
  {
    name: "California Burrito",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "prospect",
    reason: "Follow up message sent on whatsapp",
    createdAt: "2026-06-18T10:00:00.000Z",
    followUpCount: 1,
  },
  {
    name: "Sri Krishna Silks",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "June 2026",
    status: "demo",
    reason: "3rd demo for them conducted to Mr. Varun",
    createdAt: "2026-06-18T11:00:00.000Z",
    followUpCount: 1,
  },
  {
    name: "Donne Briyani",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "prospect",
    reason:
      "shared deck , need to talk wih md , but i will only get back if we require the product",
    createdAt: "2026-06-18T12:00:00.000Z",
    followUpCount: 1,
  },
  {
    name: "Rayalaseema Ruchulu",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "prospect",
    reason: "did not pick up - uttam reddy - 9849018737",
    createdAt: "2026-06-18T13:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "sport hood",
    owner: "Bhuvaneshwari",
    industry: "Fitness & Wellness",
    month: "June 2026",
    status: "prospect",
    reason: "not reachable- rahul -8129997908",
    createdAt: "2026-06-18T14:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Decathalon play",
    owner: "Bhuvaneshwari",
    industry: "Retail (General)",
    month: "June 2026",
    status: "prospect",
    reason: "no body answered",
    createdAt: "2026-06-18T15:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "The Quad fitness",
    owner: "Bhuvaneshwari",
    industry: "Fitness & Wellness",
    month: "June 2026",
    status: "prospect",
    reason: "gukan@thequad.in he will redirectwithe respective person",
    createdAt: "2026-06-18T16:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Page 3",
    owner: "Bhuvaneshwari",
    industry: "Beauty & Wellness",
    month: "June 2026",
    status: "prospect",
    reason: "followup message replied saing he is held up",
    createdAt: "2026-06-18T17:00:00.000Z",
    followUpCount: 1,
  },

  // June 19, 2026 Updates
  {
    name: "Fitness One India",
    owner: "Bhuvaneshwari",
    industry: "Fitness & Wellness",
    month: "June 2026",
    status: "prospect",
    reason: "did not pick the call",
    createdAt: "2026-06-19T10:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Sri Krishna Silks",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "June 2026",
    status: "demo",
    reason: "he will speak with his team and revert",
    createdAt: "2026-06-19T10:05:00.000Z",
    followUpCount: 2,
  },
  {
    name: "The Quad fitness",
    owner: "Bhuvaneshwari",
    industry: "Fitness & Wellness",
    month: "June 2026",
    status: "prospect",
    reason: "replied to loop email",
    createdAt: "2026-06-19T10:10:00.000Z",
    followUpCount: 1,
  },
  {
    name: "Evolve back",
    owner: "Bhuvaneshwari",
    industry: "Hospitality",
    month: "June 2026",
    status: "prospect",
    reason: "follow up email",
    createdAt: "2026-06-19T10:15:00.000Z",
    followUpCount: 1,
  },
  {
    name: "Bliss Club",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "June 2026",
    status: "prospect",
    reason: "followup email",
    createdAt: "2026-06-19T10:20:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Truffles",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "prospect",
    reason: "follow up email",
    createdAt: "2026-06-19T10:25:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Meghavi Wellness",
    owner: "Bhuvaneshwari",
    industry: "Beauty & Wellness",
    month: "June 2026",
    status: "prospect",
    reason: "follow up email ( he is in middle of something , he will look into it )",
    createdAt: "2026-06-19T10:30:00.000Z",
    followUpCount: 0,
  },
  {
    name: "KIMS (Krishna Institute)",
    owner: "Bhuvaneshwari",
    industry: "Healthcare",
    month: "June 2026",
    status: "prospect",
    reason: "speaking with someone else ( will call you back )",
    createdAt: "2026-06-19T10:35:00.000Z",
    followUpCount: 2,
  },
  {
    name: "Oliva Skin & Hair Clinic",
    owner: "Bhuvaneshwari",
    industry: "Beauty & Wellness",
    month: "June 2026",
    status: "demo",
    reason: "will get back next week",
    createdAt: "2026-06-19T10:40:00.000Z",
    followUpCount: 1,
  },
  {
    name: "Absolute Barbecues",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "prospect",
    reason: "follow up message to Gaurav",
    createdAt: "2026-06-19T10:45:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Settl",
    owner: "Bhuvaneshwari",
    industry: "Hospitality",
    month: "June 2026",
    status: "prospect",
    reason: "First call - Speaking with someone , second call - did not pick",
    createdAt: "2026-06-19T10:50:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Zolo",
    owner: "Bhuvaneshwari",
    industry: "Hospitality",
    month: "June 2026",
    status: "prospect",
    reason: "call Sadhana by 4 or 4.30",
    createdAt: "2026-06-19T10:55:00.000Z",
    followUpCount: 0,
    reminderType: "followup",
    reminderDate: "2026-06-19T16:00:00.000Z",
    reminderClosed: false,
  },
  {
    name: "Hotel Sitara Group",
    owner: "Bhuvaneshwari",
    industry: "Hospitality",
    month: "June 2026",
    status: "prospect",
    reason: "not picked",
    createdAt: "2026-06-19T11:00:00.000Z",
    followUpCount: 0,
  },
  {
    name: "MGM Hotels and Resorts",
    owner: "Bhuvaneshwari",
    industry: "Hospitality",
    month: "June 2026",
    status: "prospect",
    reason: "Share deck via Whatsapp",
    createdAt: "2026-06-19T11:05:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Purple Cloud Hotels",
    owner: "Bhuvaneshwari",
    industry: "Hospitality",
    month: "June 2026",
    status: "prospect",
    reason:
      "Herman Crasto: We are also purple cloud hotels, currently working on GMB. Whatsapp message sent, email sent with deck to the mail ID he shared",
    createdAt: "2026-06-19T11:10:00.000Z",
    followUpCount: 0,
  },

  // June 22, 2026 Updates
  {
    name: "The Quad fitness",
    owner: "Bhuvaneshwari",
    industry: "Fitness & Wellness",
    month: "June 2026",
    status: "prospect",
    reason:
      "follow up email sent , requesting for their availability - Thursday 1 to 1.30 pm but they rescheduled it",
    createdAt: "2026-06-22T10:00:00.000Z",
    followUpCount: 2,
    reminderType: "followup",
    reminderDate: "2026-06-25T13:00:00.000Z",
    reminderClosed: false,
  },
  {
    name: "Purple Cloud Hotels",
    owner: "Bhuvaneshwari",
    industry: "Hospitality",
    month: "June 2026",
    status: "prospect",
    reason: "follow up email sent",
    createdAt: "2026-06-22T10:10:00.000Z",
    followUpCount: 1,
  },
  {
    name: "California Burrito",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "prospect",
    reason: "will connect wednesday 10.00 am",
    createdAt: "2026-06-22T10:20:00.000Z",
    followUpCount: 2,
    reminderType: "followup",
    reminderDate: "2026-06-24T10:00:00.000Z",
    reminderClosed: false,
  },
  {
    name: "Cascade",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "prospect",
    reason:
      "kamala kannan - area manager 9150622286 - send a pre recorded video i will check and revert",
    createdAt: "2026-06-22T10:30:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Geetham Veg Restaurant",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "prospect",
    reason:
      "send the deck , linkedin details ( pre recorded video ), contact muthukumar senior marketing manager - 9142000500",
    createdAt: "2026-06-22T10:40:00.000Z",
    followUpCount: 0,
  },
  {
    name: "Paragon Restaurant",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "prospect",
    reason: "Share deck through whatsapp to Rathesh - RGM - 9526128809",
    createdAt: "2026-06-22T10:50:00.000Z",
    followUpCount: 0,
  },
  {
    name: "VST Motors",
    owner: "Bhuvaneshwari",
    industry: "Automotive",
    month: "June 2026",
    status: "new_lead",
    reason: "did not pick the call",
    createdAt: "2026-06-23T10:00:00.000Z",
  },
  {
    name: "KUN Exclusive",
    owner: "Bhuvaneshwari",
    industry: "Automotive",
    month: "June 2026",
    status: "new_lead",
    reason:
      "Dayanand - digital marketing - 9043722013 Share deck via whatsapp, followup call by 2pm . Tomorrow im litttle busy",
    createdAt: "2026-06-23T10:00:00.000Z",
  },
  {
    name: "asian Footwear pvt ltd",
    owner: "Bhuvaneshwari",
    industry: "Apparel & Footwear",
    month: "June 2026",
    status: "new_lead",
    reason: "speaking with someone else",
    createdAt: "2026-06-23T10:00:00.000Z",
  },
  {
    name: "California Burrito",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "demo",
    reason: "confirmed meeting by 10am on wednesday",
    createdAt: "2026-06-23T10:00:00.000Z",
  },
  {
    name: "Absolute Barbecue",
    owner: "Bhuvaneshwari",
    industry: "Food & Beverage",
    month: "June 2026",
    status: "new_lead",
    reason: "Follow up message on Whatsapp did not pick the call",
    createdAt: "2026-06-23T10:00:00.000Z",
  },
];

export const PATCH_ACCOUNTS: Account[] = newDataRaw.map((a, i) => ({
  ...a,
  status: a.status as AccountStatus,
  reminderType: a.reminderType as "none" | "reach_again" | "followup" | undefined,
  id: `patch-v3-${i}`,
}));

export const SEED_ACCOUNTS: Account[] = [
  ...raw.map((a, i) => ({ ...a, id: `seed-${i}` })),
  ...PATCH_ACCOUNTS,
];

export const SEED_REPS: SalesRep[] = [
  { name: "Bhuvaneshwari", color: "blue" },
];

export const ALL_MONTHS = Array.from(new Set(SEED_ACCOUNTS.map((a) => a.month)));
