import type { Account, AccountStatus } from "./types";

type Seed = Omit<Account, "id"> & { status: AccountStatus };

const raw: Seed[] = [
  { name: "Adinn Advertising", owner: "Bhuvaneshwari", industry: "Digital Marketing", month: "April 2026", status: "prospect", reason: "Follow up" },
  { name: "AGR / Arabian Garden", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "April 2026", status: "rejected", reason: "Did not pick initially, later said product not required and they focus on outdoor marketing" },
  { name: "Ajfan", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "April 2026", status: "prospect", reason: "Follow up" },
  { name: "ARAMYA", owner: "Om Prakash", industry: "Other", month: "April 2026", status: "prospect", reason: "Asked to share proposal via email" },
  { name: "Aravind IVF", owner: "Om Prakash", industry: "Healthcare", month: "April 2026", status: "rejected", reason: "Managing through GMB dashboard" },
  { name: "Arvind Fashion Limited", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "April 2026", status: "prospect", reason: "Shared pitch deck through WhatsApp" },
  { name: "AVR Swarna Mahal", owner: "Bhuvaneshwari", industry: "Jewellery Retail", month: "April 2026", status: "prospect", reason: "Follow up pending" },
  { name: "Bajaj Electronics", owner: "Om Prakash", industry: "Electronics Retail", month: "April 2026", status: "prospect", reason: "Using multiple tools, team may try trial version" },
  { name: "Banana Club", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "April 2026", status: "prospect", reason: "Travelling, will get back later" },
  { name: "Big Scoop Cafe", owner: "Om Prakash", industry: "Food & Beverage", month: "April 2026", status: "prospect", reason: "Will get back if required in future" },
  { name: "Cafe Coffee Day", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "April 2026", status: "prospect", reason: "PPT shared through email" },
  { name: "Chai Kaapi", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "April 2026", status: "prospect", reason: "Shared deck over LinkedIn" },
  { name: "Chennai Mobiles", owner: "Venkat", industry: "Electronics Retail", month: "April 2026", status: "rejected", reason: "No requirement for now" },
  { name: "COCO TANG", owner: "Om Prakash", industry: "Food & Beverage", month: "April 2026", status: "rejected", reason: "No requirement currently due to tourism location" },
  { name: "Cookieman", owner: "Venkat", industry: "Food & Beverage", month: "April 2026", status: "demo", reason: "Demo Completed" },
  { name: "Cream Stone", owner: "Venkat", industry: "Food & Beverage", month: "April 2026", status: "prospect", reason: "PPT not shared, will get back if required" },
  { name: "Curefit", owner: "Bhuvaneshwari", industry: "Fitness & Wellness", month: "April 2026", status: "prospect", reason: "Follow up" },
  { name: "Damro Furniture", owner: "Om Prakash", industry: "Furniture Retail", month: "April 2026", status: "rejected", reason: "Franchisees manage stores" },
  { name: "Derbymen", owner: "Om Prakash", industry: "Apparel & Footwear", month: "April 2026", status: "rejected", reason: "Not interested" },
  { name: "Edify Education - Rajesh Kumar", owner: "Om Prakash", industry: "Education", month: "April 2026", status: "rejected", reason: "Number does not exist" },
  { name: "Edify Education - Dr. Aditi Singh Thakur", owner: "Om Prakash", industry: "Education", month: "April 2026", status: "prospect", reason: "Did not pick" },
  { name: "Educadd Learning Solutions", owner: "Om Prakash", industry: "Education", month: "April 2026", status: "prospect", reason: "Busy with admissions, follow up later" },
  { name: "FIGAROS'S PIZZA", owner: "Om Prakash", industry: "Food & Beverage", month: "April 2026", status: "prospect", reason: "Call on Wednesday 3 PM" },
  { name: "First Cry", owner: "Bhuvaneshwari", industry: "Retail (General)", month: "April 2026", status: "prospect", reason: "Email sent" },
  { name: "Girias", owner: "Bhuvaneshwari", industry: "Electronics Retail", month: "April 2026", status: "prospect", reason: "Find the right contact" },
  { name: "HALF BILLION DOLLAR VENTURES", owner: "Om Prakash", industry: "Other", month: "April 2026", status: "prospect", reason: "Call after 5 PM, later did not pick" },
  { name: "Hatsun", owner: "Om Prakash", industry: "Food Processing", month: "April 2026", status: "rejected", reason: "Using Promanage" },
  { name: "Hatti Kaapi", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "April 2026", status: "prospect", reason: "Shared pricing and pitch deck through WhatsApp" },
  { name: "HazelNut Factory", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "April 2026", status: "prospect", reason: "Shared PPT, follow up needed" },
  { name: "House of Rare", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "April 2026", status: "prospect", reason: "Shared PPT over LinkedIn" },
  { name: "IGO AGRITECHFARMS", owner: "Om Prakash", industry: "Other", month: "April 2026", status: "prospect", reason: "Messaged on LinkedIn" },
  { name: "Indian Terrain", owner: "Om Prakash", industry: "Apparel & Footwear", month: "April 2026", status: "prospect", reason: "Asked to call after 3 PM, later did not pick" },
  { name: "Indira IVF Fertility Centre", owner: "Om Prakash", industry: "Healthcare", month: "April 2026", status: "prospect", reason: "Follow up at 5 PM" },
  { name: "KAG", owner: "Bhuvaneshwari", industry: "Other", month: "April 2026", status: "prospect", reason: "Not the right contact, others unavailable" },
  { name: "Kaya Skin Clinic", owner: "Om Prakash", industry: "Beauty & Wellness", month: "April 2026", status: "prospect", reason: "No update" },
  { name: "Kun Motor Company", owner: "Om Prakash", industry: "Automotive", month: "April 2026", status: "prospect", reason: "Contract" },
  { name: "Kushals", owner: "Bhuvaneshwari", industry: "Jewellery Retail", month: "April 2026", status: "demo", reason: "Demo Completed" },
  { name: "Lalitha Jewellery", owner: "Om Prakash", industry: "Jewellery Retail", month: "April 2026", status: "prospect", reason: "Warm lead, possible demo in May" },
  { name: "Manipal Health / Hospitals", owner: "Bhuvaneshwari", industry: "Healthcare", month: "April 2026", status: "prospect", reason: "Asked to call tomorrow at 10 AM, follow up pending" },
  { name: "Maple Bear - Gaurav Sharma", owner: "Om Prakash", industry: "Education", month: "April 2026", status: "prospect", reason: "Occupied" },
  { name: "Maple Bear - Anuj Bhatia", owner: "Om Prakash", industry: "Education", month: "April 2026", status: "prospect", reason: "Asked to share proposal and follow up Monday" },
  { name: "Maple Bear - Priya Bisht", owner: "Om Prakash", industry: "Education", month: "April 2026", status: "prospect", reason: "Switched off" },
  { name: "Mc Kingstown", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "April 2026", status: "prospect", reason: "PPT not shared, will get back if required" },
  { name: "Mera Laundry", owner: "Om Prakash", industry: "Laundry Services", month: "April 2026", status: "rejected", reason: "Not interested" },
  { name: "Minister White", owner: "Venkat", industry: "Apparel & Footwear", month: "April 2026", status: "demo", reason: "Demo Completed" },
  { name: "Motilal Oswal", owner: "Bhuvaneshwari", industry: "Financial Services", month: "April 2026", status: "prospect", reason: "Find the right contact" },
  { name: "Mr Blue", owner: "Om Prakash", industry: "Laundry Services", month: "April 2026", status: "rejected", reason: "No requirement for current business scale" },
  { name: "Nexa Kalyani", owner: "Om Prakash", industry: "Automotive", month: "April 2026", status: "rejected", reason: "Marketing handled by head team" },
  { name: "Oliva Skin & Hair Clinic", owner: "Om Prakash", industry: "Beauty & Wellness", month: "April 2026", status: "prospect", reason: "Interested, follow up after 2 weeks" },
  { name: "Pai International Electronics", owner: "Om Prakash", industry: "Electronics Retail", month: "April 2026", status: "prospect", reason: "Follow up after summer" },
  { name: "Paragon", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "April 2026", status: "prospect", reason: "Follow up" },
  { name: "Paulsons Group", owner: "Venkat", industry: "Food & Beverage", month: "April 2026", status: "rejected", reason: "Franchise owners manage stores individually" },
  { name: "Polar Bear", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "April 2026", status: "prospect", reason: "Follow up" },
  { name: "Poorvika", owner: "Om Prakash", industry: "Electronics Retail", month: "April 2026", status: "prospect", reason: "Contact Sudhir after 2 PM on 29.04.2026" },
  { name: "Popees", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "April 2026", status: "demo", reason: "Demo Completed" },
  { name: "Prisma", owner: "Bhuvaneshwari", industry: "Digital/Advertising", month: "April 2026", status: "prospect", reason: "Check for right contact" },
  { name: "Rainbow Hospital", owner: "Bhuvaneshwari", industry: "Healthcare", month: "April 2026", status: "prospect", reason: "Follow up" },
  { name: "Ramraj Cotton", owner: "Om Prakash", industry: "Apparel & Footwear", month: "April 2026", status: "rejected", reason: "Using another product/tool" },
  { name: "Royal Enfield", owner: "Bhuvaneshwari", industry: "Automotive", month: "April 2026", status: "demo", reason: "Demo Completed" },
  { name: "Sai Silks Kalamandir", owner: "Venkat", industry: "Apparel & Footwear", month: "April 2026", status: "prospect", reason: "Shared email" },
  { name: "Sakhiya Skin Clinic", owner: "Om Prakash", industry: "Beauty & Wellness", month: "April 2026", status: "prospect", reason: "No update" },
  { name: "SANFORT WORLD GLOBAL", owner: "Om Prakash", industry: "Education", month: "April 2026", status: "prospect", reason: "Did not pick" },
  { name: "Sangeetha Mobiles", owner: "Om Prakash", industry: "Electronics Retail", month: "April 2026", status: "prospect", reason: "Not responding" },
  { name: "Siyaram", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "April 2026", status: "rejected", reason: "Did not pick, no current requirement" },
  { name: "Soch Apparels", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "April 2026", status: "prospect", reason: "Sent pitch deck, follow up pending" },
  { name: "Souled Store", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "April 2026", status: "prospect", reason: "Did not pick the call" },
  { name: "Style Spa Furniture Ltd", owner: "Om Prakash", industry: "Furniture Retail", month: "April 2026", status: "rejected", reason: "Already using another tool" },
  { name: "Surya Nissan and Datsun Car", owner: "Om Prakash", industry: "Automotive", month: "April 2026", status: "prospect", reason: "Contract" },
  { name: "Technosport", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "April 2026", status: "prospect", reason: "Shared responsible department contact" },
  { name: "Thangamayil Jewellery", owner: "Bhuvaneshwari", industry: "Jewellery Retail", month: "April 2026", status: "demo", reason: "Demo Completed" },
  { name: "THE COFFEE EVOLUTION", owner: "Om Prakash", industry: "Food & Beverage", month: "April 2026", status: "prospect", reason: "Marketing team will reach out" },
  { name: "TTK Prestige", owner: "Bhuvaneshwari", industry: "Retail (General)", month: "April 2026", status: "demo", reason: "Demo Completed" },
  { name: "Veranda RACE", owner: "Bhuvaneshwari", industry: "Education", month: "April 2026", status: "prospect", reason: "Connected through LinkedIn" },
  { name: "Viveks", owner: "Om Prakash", industry: "Electronics Retail", month: "April 2026", status: "rejected", reason: "Already using another tool" },
  { name: "Vmart", owner: "Om Prakash", industry: "Supermarket & Grocery", month: "April 2026", status: "rejected", reason: "Call not continuing" },
  { name: "WASH GUYS", owner: "Om Prakash", industry: "Laundry Services", month: "April 2026", status: "prospect", reason: "Call back scheduled at 12 PM" },
  { name: "Wrogn", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "April 2026", status: "prospect", reason: "Shared pitch deck through WhatsApp" },
  { name: "Dr. Smilez Dental Group", owner: "Bhuvaneshwari", industry: "Healthcare", month: "April 2026", status: "demo", reason: "Demo Completed" },
  { name: "Kongsi Tea Bar", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "April 2026", status: "demo", reason: "Demo Completed" },
  { name: "KIMS Hospital", owner: "Bhuvaneshwari", industry: "Healthcare", month: "April 2026", status: "demo", reason: "Demo Completed" },
  { name: "Rainbow Hospital", owner: "Bhuvaneshwari", industry: "Healthcare", month: "Feb to March 2026", status: "prospect", reason: "Follow up" },
  { name: "Girias", owner: "Bhuvaneshwari", industry: "Electronics Retail", month: "Feb to March 2026", status: "prospect", reason: "Find the right contact" },
  { name: "Curefit", owner: "Bhuvaneshwari", industry: "Fitness & Wellness", month: "Feb to March 2026", status: "prospect", reason: "Follow up" },
  { name: "Hatti Kaapi", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect", reason: "Sent the pitch deck through WA" },
  { name: "Adinn Advertising", owner: "Bhuvaneshwari", industry: "Digital Marketing", month: "Feb to March 2026", status: "prospect", reason: "Follow up" },
  { name: "Prisma", owner: "Bhuvaneshwari", industry: "Digital/Advertising", month: "Feb to March 2026", status: "prospect", reason: "Check for right contact" },
  { name: "Popees", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect", reason: "Follow up" },
  { name: "TTK Prestige", owner: "Bhuvaneshwari", industry: "Retail (General)", month: "Feb to March 2026", status: "prospect", reason: "Follow up" },
  { name: "First Cry", owner: "Bhuvaneshwari", industry: "Retail (General)", month: "Feb to March 2026", status: "prospect", reason: "Email sent" },
  { name: "Arabian Garden", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect", reason: "Call after election" },
  { name: "Sai Silks Kalamandir", owner: "Venkat", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect", reason: "Shared Email" },
  { name: "AVR Swarna Mahal", owner: "Bhuvaneshwari", industry: "Jewellery Retail", month: "Feb to March 2026", status: "prospect", reason: "Follow Up" },
  { name: "Cream Stone", owner: "Venkat", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect", reason: "PPT Not shared, Will get back if required." },
  { name: "Royal Enfield", owner: "Bhuvaneshwari", industry: "Automotive", month: "Feb to March 2026", status: "demo", reason: "Demo Completed" },
  { name: "House of Rare", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect", reason: "Shared PPT over LinkedIn" },
  { name: "Ethnix by Reymand", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "rejected", reason: "Using another product" },
  { name: "Ramraj Cotton", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "rejected", reason: "Using another product" },
  { name: "Derbymen", owner: "Aswini", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect", reason: "Not started anything" },
  { name: "Technosport", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect", reason: "Check for right contact" },
  { name: "5k Care Car", owner: "Aswini", industry: "Automotive Services", month: "Feb to March 2026", status: "prospect" },
  { name: "Vcare", owner: "Bhuvaneshwari", industry: "Beauty & Wellness", month: "Feb to March 2026", status: "prospect" },
  { name: "Health & Glow", owner: "Bhuvaneshwari", industry: "Beauty & Wellness", month: "Feb to March 2026", status: "prospect" },
  { name: "Marie Claire", owner: "Aswini", industry: "Beauty & Wellness", month: "Feb to March 2026", status: "prospect" },
  { name: "The Building Doctor", owner: "Aswini", industry: "Construction", month: "Feb to March 2026", status: "demo" },
  { name: "The Building Doctor", owner: "Aswini", industry: "Construction", month: "April 2026", status: "trial" },
  { name: "Digitmarket", owner: "Aswini", industry: "Digital Marketing", month: "Feb to March 2026", status: "prospect" },
  { name: "Woodhead", owner: "Aswini", industry: "Digital Marketing", month: "Feb to March 2026", status: "prospect" },
  { name: "Metamorphisi Preschool", owner: "Aswini", industry: "Education", month: "Feb to March 2026", status: "demo", reason: "Follow up for onboarding" },
  { name: "Veranda RACE", owner: "Bhuvaneshwari", industry: "Education", month: "Feb to March 2026", status: "prospect" },
  { name: "CADD Centre", owner: "Bhuvaneshwari", industry: "Education", month: "Feb to March 2026", status: "prospect" },
  { name: "IRIS Florets", owner: "Aswini", industry: "Education", month: "Feb to March 2026", status: "prospect" },
  { name: "Sathya", owner: "Bhuvaneshwari", industry: "Electronics Retail", month: "Feb to March 2026", status: "prospect" },
  { name: "Viveks", owner: "Bhuvaneshwari", industry: "Electronics Retail", month: "Feb to March 2026", status: "rejected", reason: "Already using another tool" },
  { name: "Snitch", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect" },
  { name: "My Cash Easy", owner: "Aswini", industry: "Financial Services", month: "Feb to March 2026", status: "prospect" },
  { name: "Cothas Coffee", owner: "Venkat", industry: "Food & Beverage", month: "Feb to March 2026", status: "demo", reason: "Occupied. Reconnect on 10th for onboarding" },
  { name: "The Falooda", owner: "Aswini", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect" },
  { name: "Food Mohalla", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "Feb to March 2026", status: "rejected", reason: "Not interested" },
  { name: "Bombay Kulfi", owner: "Aswini", industry: "Food & Beverage", month: "Feb to March 2026", status: "demo" },
  { name: "Aaladipattiyan", owner: "Venkat", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect" },
  { name: "A2B", owner: "Venkat", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect" },
  { name: "Haldiram's", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect" },
  { name: "Mr Sandwich", owner: "Aswini", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect" },
  { name: "Chai Kaapi", owner: "Aswini", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect" },
  { name: "Frozen Bottle", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "Feb to March 2026", status: "rejected", reason: "Having separate agency" },
  { name: "Anjappar Chettinad", owner: "Aswini", industry: "Food & Beverage", month: "Feb to March 2026", status: "demo", reason: "Using competitors product - Famepilot. Connect on Whatsapp" },
  { name: "Franks Hot Dogs", owner: "Aswini", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect" },
  { name: "Arbain Sea Food", owner: "Aswini", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect" },
  { name: "Polar Bear", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect", reason: "Follow Up" },
  { name: "COCO TANG", owner: "Aswini", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect" },
  { name: "Cookieman", owner: "Venkat", industry: "Food & Beverage", month: "Feb to March 2026", status: "demo", reason: "Demo Completed, will get back if any requirement" },
  { name: "Smoothie Factory", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect" },
  { name: "Cafe Coffee Day", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "Feb to March 2026", status: "rejected", reason: "PPT shared over email" },
  { name: "Suto Cafe", owner: "Aswini", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect", reason: "Sent the proposal to her whatsapp, follow up pending" },
  { name: "Barbeque Nation", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect" },
  { name: "Burgerman", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect" },
  { name: "Uncle Peter's Pancakes", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect" },
  { name: "Paragon", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect", reason: "Follow up" },
  { name: "Topi Vappa Biriyani", owner: "Aswini", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect" },
  { name: "Ajfan", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect", reason: "Follow Up" },
  { name: "Suguna Foods Private Limited", owner: "Bhuvaneshwari", industry: "Food Processing", month: "Feb to March 2026", status: "prospect" },
  { name: "Royaloak", owner: "Bhuvaneshwari", industry: "Furniture Retail", month: "Feb to March 2026", status: "rejected", reason: "Using Another product" },
  { name: "Aarthi Scans & Labs", owner: "Bhuvaneshwari", industry: "Healthcare", month: "Feb to March 2026", status: "prospect" },
  { name: "Dr. Agarwals", owner: "Bhuvaneshwari", industry: "Healthcare", month: "Feb to March 2026", status: "prospect" },
  { name: "Nueberg", owner: "Bhuvaneshwari", industry: "Healthcare", month: "Feb to March 2026", status: "rejected", reason: "Using another product" },
  { name: "Aravind IVF", owner: "Bhuvaneshwari", industry: "Healthcare", month: "Feb to March 2026", status: "prospect" },
  { name: "Clove Dental", owner: "Bhuvaneshwari", industry: "Healthcare", month: "Feb to March 2026", status: "rejected", reason: "Internal Management" },
  { name: "Neemrana Hotels Pvt Ltd", owner: "Bhuvaneshwari", industry: "Hospitality", month: "Feb to March 2026", status: "rejected", reason: "Not interested" },
  { name: "Bhima Gold", owner: "Bhuvaneshwari", industry: "Jewellery Retail", month: "Feb to March 2026", status: "prospect" },
  { name: "UClean", owner: "Aswini", industry: "Laundry Services", month: "Feb to March 2026", status: "prospect" },
  { name: "La Lavanderia", owner: "Aswini", industry: "Laundry Services", month: "Feb to March 2026", status: "prospect" },
  { name: "Laundry To", owner: "Aswini", industry: "Laundry Services", month: "Feb to March 2026", status: "prospect" },
  { name: "Dhobilite Laundry", owner: "Aswini", industry: "Laundry Services", month: "Feb to March 2026", status: "prospect" },
  { name: "Specsmakers", owner: "Bhuvaneshwari", industry: "Healthcare", month: "Feb to March 2026", status: "rejected", reason: "Using another product" },
  { name: "Med Plus", owner: "Bhuvaneshwari", industry: "Healthcare", month: "Feb to March 2026", status: "prospect" },
  { name: "Poppees Baby Care", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect", reason: "Follow up" },
  { name: "Mr Blue", owner: "Aswini", industry: "Laundry Services", month: "Feb to March 2026", status: "prospect" },
  { name: "Presto", owner: "Bhuvaneshwari", industry: "Retail (General)", month: "Feb to March 2026", status: "prospect" },
  { name: "KPN Fresh", owner: "Venkat", industry: "Retail (General)", month: "Feb to March 2026", status: "prospect" },
  { name: "Darling Retail", owner: "Bhuvaneshwari", industry: "Retail (General)", month: "Feb to March 2026", status: "prospect" },
  { name: "Born Babies", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect" },
  { name: "Wrogn", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect", reason: "Shared the pitch deck through WA" },
  { name: "Indian Terrain", owner: "Aswini", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect", reason: "Call after 3pm" },
  { name: "Odyssey India Ltd.", owner: "Aswini", industry: "Retail (General)", month: "Feb to March 2026", status: "prospect" },
  { name: "Chennai Mobiles", owner: "Venkat", industry: "Electronics Retail", month: "Feb to March 2026", status: "rejected", reason: "No need for now" },
  { name: "Westside", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect" },
  { name: "Grocery 4 U Retail", owner: "Aswini", industry: "Supermarket & Grocery", month: "Feb to March 2026", status: "prospect" },
  { name: "Kushal's Fashion Jewellery", owner: "Bhuvaneshwari", industry: "Jewellery Retail", month: "Feb to March 2026", status: "prospect" },
  { name: "Puma", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect" },
  { name: "Spar", owner: "Bhuvaneshwari", industry: "Supermarket & Grocery", month: "Feb to March 2026", status: "prospect" },
  { name: "Zudio", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect" },
  { name: "Laundrex", owner: "Bhuvaneshwari", industry: "Laundry Services", month: "Feb to March 2026", status: "prospect" },
  { name: "Pick My Laundry", owner: "Aswini", industry: "Laundry Services", month: "Feb to March 2026", status: "prospect" },
  { name: "Green Trends", owner: "Aswini", industry: "Beauty & Wellness", month: "Feb to March 2026", status: "prospect" },
  { name: "GRT Jewellery", owner: "Bhuvaneshwari", industry: "Jewellery Retail", month: "Feb to March 2026", status: "prospect" },
  { name: "Chai Kaapi", owner: "Aswini", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect" },
  { name: "Max Fashion India", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect" },
  { name: "Pantaloons", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect" },
  { name: "Zivame", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect" },
  { name: "Cheese and Co", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect" },
  { name: "Croma", owner: "Aswini", industry: "Electronics Retail", month: "Feb to March 2026", status: "prospect", reason: "Not started anything" },
  { name: "Lifestyle Stores - Easy Buy", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect" },
  { name: "Licious", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect" },
  { name: "Kongsi Tea Bar", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "Feb to March 2026", status: "trial" },
  { name: "Thangamayil Jewellery", owner: "Bhuvaneshwari", industry: "Jewellery Retail", month: "Feb to March 2026", status: "demo" },
  { name: "Boba Bhai", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "Feb to March 2026", status: "rejected", reason: "Not needed right now" },
  { name: "Palmonas", owner: "Bhuvaneshwari", industry: "Jewellery Retail", month: "Feb to March 2026", status: "prospect" },
  { name: "Mc Kingstown", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect", reason: "PPT not shared, will get back if required" },
  { name: "Hazel Nut Factory", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect", reason: "Shared the ppt, need to follow up" },
  { name: "Naadbramha Idli", owner: "Aswini", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect" },
  { name: "Rare Rabbit", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect", reason: "Shared ppt over LinkedIn" },
  { name: "Madras Coffee House", owner: "Aswini", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect" },
  { name: "Kalyan Jewellers", owner: "Aswini", industry: "Jewellery Retail", month: "Feb to March 2026", status: "prospect" },
  { name: "Titan Eyeplus", owner: "Aswini", industry: "Healthcare", month: "Feb to March 2026", status: "prospect" },
  { name: "Fabindia", owner: "Aswini", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect" },
  { name: "Joyalukkas", owner: "Aswini", industry: "Jewellery Retail", month: "Feb to March 2026", status: "prospect" },
  { name: "Dindigul Thalappakatti Restaurant", owner: "Aswini", industry: "Food & Beverage", month: "Feb to March 2026", status: "prospect", reason: "Sent the proposal to his whatsapp, cold called him" },
  { name: "Anytime Fitness", owner: "Aswini", industry: "Beauty & Wellness", month: "Feb to March 2026", status: "prospect" },
  { name: "Edify Education", owner: "Aswini", industry: "Education", month: "Feb to March 2026", status: "prospect", reason: "Did not pick" },
  { name: "Minister White", owner: "Venkat", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "demo", reason: "Demo Completed, need to follow up" },
  { name: "i Tooth Dental Clinic", owner: "Bhuvaneshwari", industry: "Healthcare", month: "Feb to March 2026", status: "prospect" },
  { name: "Maybell", owner: "Bhuvaneshwari", industry: "Beauty & Wellness", month: "Feb to March 2026", status: "prospect" },
  { name: "Alldone Laundromat & Dry Cleaning", owner: "Aswini", industry: "Laundry Services", month: "Feb to March 2026", status: "prospect" },
  { name: "TIME4education", owner: "Aswini", industry: "Education", month: "Feb to March 2026", status: "prospect" },
  { name: "Mera Laundry", owner: "Aswini", industry: "Laundry Services", month: "Feb to March 2026", status: "demo", reason: "Sent Whatsapp message to him for onboarding" },
  { name: "FABO", owner: "Aswini", industry: "Laundry Services", month: "Feb to March 2026", status: "prospect" },
  { name: "Dr. Smilez Dental Group", owner: "Bhuvaneshwari", industry: "Healthcare", month: "Feb to March 2026", status: "demo" },
  { name: "Damro Furniture", owner: "Aswini", industry: "Furniture Retail", month: "Feb to March 2026", status: "prospect" },
  { name: "Banana Club", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect" },
  { name: "Wildcraft", owner: "Aswini", industry: "Apparel & Footwear", month: "Feb to March 2026", status: "prospect", reason: "Sent the proposal to email id" },
  { name: "Sangeetha Mobile", owner: "Aswini", industry: "Electronics Retail", month: "Feb to March 2026", status: "prospect" },
  { name: "Mr.DIY", owner: "Aswini", industry: "Retail (General)", month: "Feb to March 2026", status: "demo", reason: "Demo done, he said he doesn't know us" },
];

const newDataRaw = [
  { name: "KIMS Hospital", owner: "Bhuvaneshwari", industry: "Healthcare", month: "May 2026", status: "prospect", reason: "Today he has appointment, so follow up after 12pm tom. to check for demo", createdAt: "2026-05-04T12:00:00.000Z" },
  { name: "Soch Apparels", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "May 2026", status: "prospect", reason: "Call after some time", createdAt: "2026-05-04T12:00:00.000Z" },
  { name: "Alldone Laundromat & Dry Cleaning", owner: "Om Prakash", industry: "Laundromat", month: "May 2026", status: "prospect", reason: "Need to follow back on thursday", createdAt: "2026-05-04T12:00:00.000Z" },
  { name: "Dhobilite Laundry", owner: "Om Prakash", industry: "Laundromat", month: "May 2026", status: "rejected", reason: "Not interested", createdAt: "2026-05-04T12:00:00.000Z" },
  { name: "Landmark Cars", owner: "Om Prakash", industry: "Automotive", month: "May 2026", status: "prospect", reason: "Abhishek Iyer Head Of Marketing Communications - He said they have enough man power , but he might convert if we pitch again", createdAt: "2026-05-04T12:00:00.000Z" },
  { name: "Nandhi Toyota", owner: "Om Prakash", industry: "Automotive", month: "May 2026", status: "prospect", reason: "Sri Harsha Vijayakumar - CORPORATE SALES TERRITORY HEAD - They asked for our website  , they will get back to us within 2 or 3 weeks", createdAt: "2026-05-04T12:00:00.000Z" },
  { name: "Kauvery Hospital", owner: "Bhuvaneshwari", industry: "Healthcare", month: "May 2026", status: "prospect", reason: "Follow up made", createdAt: "2026-05-05T12:00:00.000Z" },
  { name: "Khazana Jewellery", owner: "Bhuvaneshwari", industry: "Jewellery", month: "May 2026", status: "prospect", reason: "Shared pitch deck through mail id, follow up after 2 days (they already have tools for all the activities)", createdAt: "2026-05-05T12:00:00.000Z" },
  { name: "TTK Prestige", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "May 2026", status: "prospect", reason: "Make a follow up call after demo - Did not pick the call", createdAt: "2026-05-05T12:00:00.000Z" },
  { name: "Popees", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "May 2026", status: "prospect", reason: "He is in a meeting, call back later", createdAt: "2026-05-05T12:00:00.000Z" },
  { name: "Trident Auto", owner: "Om Prakash", industry: "Automotive", month: "May 2026", status: "rejected", reason: "Not Interested", createdAt: "2026-05-05T12:00:00.000Z" },
  { name: "Ola Electric", owner: "Om Prakash", industry: "Automotive", month: "May 2026", status: "rejected", reason: "Not Interested", createdAt: "2026-05-05T12:00:00.000Z" },
  { name: "Ather Space", owner: "Om Prakash", industry: "Automotive", month: "May 2026", status: "rejected", reason: "Not Interested", createdAt: "2026-05-05T12:00:00.000Z" },
  { name: "Technosport", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "May 2026", status: "rejected", reason: "He tried our product through our website, they did not like our dashboard", createdAt: "2026-05-05T12:00:00.000Z" },
  { name: "KIMS Hospital", owner: "Bhuvaneshwari", industry: "Healthcare", month: "May 2026", status: "prospect", reason: "Since there were issues in connecting could not conduct the demo meeting.", createdAt: "2026-05-05T12:00:00.000Z" },
  { name: "Hatti Kaapi", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "May 2026", status: "prospect", reason: "Follow Up Made", createdAt: "2026-05-05T12:00:00.000Z" },
  { name: "TTK Prestige", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "May 2026", status: "prospect", reason: "Sent Follow up email. (Mr Abhishek has requested to continue any further discussion through mail only)", createdAt: "2026-05-06T12:00:00.000Z" },
  { name: "KAG", owner: "Bhuvaneshwari", industry: "Other", month: "May 2026", status: "prospect", reason: "Sent mail to info@kagindia.com as per their suggestion.", createdAt: "2026-05-06T12:00:00.000Z" },
  { name: "KIMS Hospital", owner: "Bhuvaneshwari", industry: "Healthcare", month: "May 2026", status: "prospect", reason: "Follow Up Made, He had asked me to call tom after 11 AM", createdAt: "2026-05-06T12:00:00.000Z" },
  { name: "RMKV Silks", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "May 2026", status: "prospect", reason: "Call back on tuesday after texting on WA", createdAt: "2026-05-06T12:00:00.000Z" },
  { name: "Nalli Silks", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "May 2026", status: "new_lead", reason: "Not required right now but shared the deck through mail", createdAt: "2026-05-06T12:00:00.000Z" },
  { name: "Chennai Silks", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "May 2026", status: "new_lead", reason: "Not a right contact", createdAt: "2026-05-06T12:00:00.000Z" },
  { name: "ABFRL", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "May 2026", status: "prospect", reason: "Call back on wednesday 13/05 after 2 pm", createdAt: "2026-05-06T12:00:00.000Z" },
  { name: "Joy Alukkas", owner: "Bhuvaneshwari", industry: "Jewellery", month: "May 2026", status: "prospect", reason: "Shared deck through WA", createdAt: "2026-05-07T12:00:00.000Z" },
  { name: "Kankatala Textiles", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "May 2026", status: "new_lead", reason: "Call after 6 pm", createdAt: "2026-05-07T12:00:00.000Z" },
  { name: "KIMS Hospital", owner: "Bhuvaneshwari", industry: "Healthcare", month: "May 2026", status: "demo", reason: "Demo Completed, need to share proposal", createdAt: "2026-05-07T12:00:00.000Z" },
  { name: "Big A Solutions", owner: "Bhuvaneshwari", industry: "Digital Marketing", month: "May 2026", status: "prospect", reason: "call back after 2 days", createdAt: "2026-05-07T12:00:00.000Z" },
  { name: "Jayalakshmi Textiles", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "May 2026", status: "new_lead", reason: "Did not pick the call", createdAt: "2026-05-07T12:00:00.000Z" },
  { name: "Neerus", owner: "Bhuvaneshwari", industry: "Other", month: "May 2026", status: "new_lead", reason: "Not Reachable", createdAt: "2026-05-07T12:00:00.000Z" },
  { name: "KIMS Hospital", owner: "Bhuvaneshwari", industry: "Healthcare", month: "May 2026", status: "proposal_sent", reason: "Shared the proposal via mail", createdAt: "2026-05-08T12:00:00.000Z" },
  { name: "Soch Apparels", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "May 2026", status: "prospect", reason: "Sent follow up message through WA", createdAt: "2026-05-08T12:00:00.000Z" },
  { name: "TTK Prestige", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "May 2026", status: "prospect", reason: "sent 2nd follow up mail", createdAt: "2026-05-08T12:00:00.000Z" },
  { name: "Popees", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "May 2026", status: "prospect", reason: "follow up email sent", createdAt: "2026-05-08T12:00:00.000Z" },
  { name: "TVS Motor Dealer Network", owner: "Bhuvaneshwari", industry: "Automotive", month: "May 2026", status: "rejected", reason: "Not Interested, They are using another platform so not needed now.", createdAt: "2026-05-08T12:00:00.000Z" },
  { name: "Kalyani Motors", owner: "Bhuvaneshwari", industry: "Automotive", month: "May 2026", status: "new_lead", reason: "Sent pitchdeck through WA", createdAt: "2026-05-08T12:00:00.000Z" },
  { name: "Advaith hyundai", owner: "Bhuvaneshwari", industry: "Automotive", month: "May 2026", status: "new_lead", reason: "Did not pick the call", createdAt: "2026-05-08T12:00:00.000Z" },
  { name: "Bimal Auto Agency", owner: "Bhuvaneshwari", industry: "Automotive", month: "May 2026", status: "new_lead", reason: "Person not working there, not picked the call", createdAt: "2026-05-08T12:00:00.000Z" },
  { name: "Deepsense Digital", owner: "Bhuvaneshwari", industry: "Digital Marketing", month: "May 2026", status: "new_lead", reason: "Shared pitchdeck with co founder", createdAt: "2026-05-08T12:00:00.000Z" },
  { name: "Adinn Advertising", owner: "Bhuvaneshwari", industry: "Digital Marketing", month: "May 2026", status: "new_lead", reason: "After May 16", createdAt: "2026-05-08T12:00:00.000Z" },
  { name: "Polar Bear", owner: "Bhuvaneshwari", industry: "Food & Beverage", month: "May 2026", status: "new_lead", reason: "He said to give him a week time", createdAt: "2026-05-08T12:00:00.000Z" },
  { name: "Arvind Fashion Limited", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "May 2026", status: "new_lead", reason: "Sent WA Reminder", createdAt: "2026-05-08T12:00:00.000Z" },
  { name: "snitch", owner: "Bhuvaneshwari", industry: "Apparel & Footwear", month: "May 2026", status: "prospect", reason: "shared deck through WA", createdAt: "2026-05-08T12:00:00.000Z" },
  { name: "Rainbow Hospital", owner: "Bhuvaneshwari", industry: "Other", month: "May 2026", status: "new_lead", reason: "Attended but no response", createdAt: "2026-05-11T12:00:00.000Z" },
  { name: "Deepsense Digital", owner: "Bhuvaneshwari", industry: "Digital Marketing", month: "May 2026", status: "new_lead", reason: "Sent WA Reminder", createdAt: "2026-05-11T12:00:00.000Z" },
  { name: "HCG (HealthCare Global Enterprises)", owner: "Bhuvaneshwari", industry: "Healthcare", month: "May 2026", status: "prospect", reason: "Call by 12pm tomorrow", createdAt: "2026-05-11T12:00:00.000Z" },
  { name: "Harsha Toyota", owner: "Om Prakash", industry: "Automotive", month: "May 2026", status: "demo", reason: "Demo completed.", createdAt: "2026-05-11T12:00:00.000Z" }
];

export const PATCH_ACCOUNTS: Account[] = newDataRaw.map((a, i) => ({
  ...a,
  status: a.status as AccountStatus,
  id: `patch-v3-${i}`
}));

export const SEED_ACCOUNTS: Account[] = [
  ...raw.map((a, i) => ({ ...a, id: `seed-${i}` })),
  ...PATCH_ACCOUNTS
];

export const SEED_REPS = [
  { name: "Bhuvaneshwari", color: "blue" as const },
  { name: "Om Prakash", color: "green" as const },
  { name: "Aswini", color: "purple" as const },
  { name: "Venkat", color: "amber" as const },
];

export const ALL_MONTHS = Array.from(
  new Set(SEED_ACCOUNTS.map((a) => a.month))
);
